### ISSUE TITLE
Is the name of the Log Stream configurable?

### ISSUE THREAD

**Issue by AndrewLane** [aws/aws-logging-dotnet#1]
Looks like the log stream name is just a timestamp with a GUID appended?  Is that correct?  Is it configurable at all?

**Comment by spati2** [comment]
You are right. We don't expose a configuration that lets you assign a log stream name. We can certainly explore that possibility. Do you think a user provided log stream name with a timestamp appended is better?

**Comment by AndrewLane** [comment]
I'm new to AWS CloudWatch, but in my experience I've seen log stream names that don't change and are the instanceId of the ec2 instance.  Just curious, why would you want your number of log streams to grow over time?

**Comment by spati2** [comment]
After a you push logs into a logstream, a next sequence token is returned that you would need as an input parameter for pushing logs into the same logstream(http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html). If the sequence token is invalid, the logging API will create a new logstream and post messages into there. So, if your current logging session is shut down either intentionally or unintentionally, only then would a new logStream be created. But going back to your earlier comment, it would be a good idea to allow the users of the API name their logstream.

**Comment by AndrewLane** [comment]
Cool.  I'm using https://github.com/camitz/CloudWatchAppender currently if want to take a look what they provide.

**Comment by KennethWKZ** [comment]
I need this too and please add custom NLog Layout Template parameters for us to redesign the message into json format

**Comment by spati2** [comment]
So the design that I am working on would let you configure the logstreamname. In CloudWatch logs your logs would then appear under a logstream such as 'CustomLogStreamName'+Timestamp. Let me know if this works for you?

**Comment by AndrewLane** [comment]
Do they HAVE to have a timestamp on the end?  Could that be the default but
also provide an option where there's no timestamp at the end?

**Comment by spati2** [comment]
So you could have multiple logstreams in your account. To discern from one logstream to another adding the timestamp makes sense

**Comment by KennethWKZ** [comment]
Currently I need logstreams name without timestamp because i already save my timestamp and others details in log event. My way to trace those events is using elastic search. You could provide an option as selective.

**Comment by emresebat** [comment]
Hi

LogGroup and LogName can be provided in other CloudWatch integrations like nodejs so I think this should be up to the developer.

CloudWatchLogsTarget project already provides these [options](https://github.com/Onalytica/CloudWatchLogsTarget/blob/master/NLog.Targets.CloudWatchLogs/NLog.config) so the official library should also have these.

**Comment by sakopov** [comment]
+1

This is a show stopper for me.

**Comment by webedge** [comment]
+1

**Comment by booman** [comment]
+1

This is a show stopper for me also.

**Comment by KennethWKZ** [comment]
any update?

**Comment by InsidiousForce** [comment]
Would be great to pass in the stream name somewhere - is this being worked on if not I really would like this feature and am willing to add it in a few weeks if no one else is currently working on it.

**Comment by asherber** [comment]
Need to have this here as well. Please do take a look at the CloudWatchAppender as referenced above, since they get a lot of things right. In particular, the group name and stream name can be set not just in configuration, but dynamically on each log message if needed. This lets a single application log to multiple groups/streams if needed. That lib also has neat ways of dealing with the next sequence token and reusing streams. It's a really great library, but I'm not sure that supporting .NET Standard is on their roadmap. I'm happy that AWS is providing an official library, but it would be nice to provide the same kind of feature set as what's already out there.

**Comment by spati2** [comment]
Thanks for the info @asherber . The current update to the logging library lets a user set the logstream name but it comes with the timestamp attached. We are currently exploring the concept of reusing the same logstream.

**Comment by KennethWKZ** [comment]
@spati2 Sorry, just wanna asking any update on resuing the same logstream?

**Comment by ahrsmnk** [comment]
Hi @spati2 , is there any updates on your side around this topic?
This option would really be helpful to me also.

Thanks

**Comment by caarl** [comment]
@spati2 / anyone, please can you direct me to the docs/an example for configuring the logstream name (with the timestamp).  Thanks.

**Comment by paulinetheitgirl** [comment]
@caarl the config property is `logStreamNameSuffix`. See https://github.com/aws/aws-logging-dotnet/blob/master/src/AWS.Logger.Core/AWSLoggerConfig.cs

**Comment by spati2** [comment]
Hi,
We have been talking to the AWS Cloudwatch team and what we arrived on is that we cannot guarantee that the same logstream would be reused. What we have instead implemented is a logic in AWS.Logger.Core that prioritizes logging in the current logstream instead of logging to a new logstream when a putlogevent request fails.  We would hence need the timestamp as a backup in the event that logging into the current logstream fails.

**Comment by davonz** [comment]
@spati2 I'm also very interested in this functionality. I have been able to achieve reuse of existing log streams within an AWS Lambda running .net core and the AWS CloudWatchLog API. In our case, the LogStreamName and LogGroup are specified in our function request and the LogGroup is queried for the latest SequenceToken, so it all seems possible. Cheers

**Comment by jesusmogollon** [comment]
Hi, any update on this feature?
I could get await with the LogStreamNameSuffix, the problem that I'm facing is that I want to put a rendered variable into the string like 
`LogStreamNameSuffix="mytrce-${machinename}"`
Unfortunately the variable doesn't get parsed it just create a new log group with the prefix and the literal mytrce-${machinename} at the end.
Is it possible to at least make this property to parse the text before creating/updating the log group? (at least on initialization)

**Comment by chipallen2** [comment]
Is there any update to this or workaround? 

The current implementation forcing a timestamp prefix in the log stream name makes this unusable since there ends up being hundreds of different log streams in our cloudwatch log group when different clients close and re-open the application. Trying to search the log group for a single log stream for one client is impossible.

**Comment by sakopov** [comment]
While this may not be ideal, one workaround would be to add some kind of customer identifier to every log entry. This would allow you to search log entries across multiple streams. If your logs are structured (ie use JSON) performing these types of searches in Cloudwatch becomes even easier.

**Comment by chipallen2** [comment]
Yeah - that's what I ended up doing. I basically took the name I wanted to call my log stream and made that a prefix to every log entry string. I researched other solutions but there really aren't any that I could find so the workaround is the best option as of this date.

**Comment by justinthomas-syncbak** [comment]
This is a huge miss for us as well.  If I have a service, even multiple instances of it, I don't was n number of log streams.  I makes it impossible to search the streams, in a useful way, without having to pipe it into another service for organizing the entries.

**Comment by piyushyadav0509** [comment]
+1 @spati2 @aws-dash do we have any update about this feature of customizing log stream name. It would help if we get this for Lambda / API-Gateway among other services. instead of the app/function-id which keeps on changing, we would like to make it custom+static and send the logs to that cloudwatch log stream.

**Comment by vashdev** [comment]
This is a show stopper for us too. I cannot believe AWS does not let us configure log streams somehow.

**Comment by mark-cohen** [comment]
This is now configurable via the "log_stream_name" value, as per: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html.

"logs":{
   "logs_collected":{
      "files":{
         "collect_list":[
            {
               "file_path":"c:\\ProgramData\\Amazon\\AmazonCloudWatchAgent\\Logs\\amazon-cloudwatch-agent.log",
               "log_group_name":"amazon-cloudwatch-agent.log",
               "log_stream_name":"my_log_stream_name_1",
               "timestamp_format":"%H:%M:%S %y %b %-d"
            },

**Comment by bisoldi** [comment]
Is there a way to have the cloudwatch agent rotate the log stream name?  For example, the stream name: `{instance_id}-{yyyy-MM}` which would create a new stream per instance for each month?  

I'm not 100% sure of the use-case for it, considering log retention capabilities and date filtering in the console, but it's what I was doing with the CW Appender, so for the time being, I was hoping to replicate that functionality.

**Comment by mchristoph** [comment]
+1 
 
A show stopper for us too.

**Comment by msegzda** [comment]
> We don't expose a configuration that lets you assign a log stream name. We can certainly explore that possibility. Do you think a user provided log stream name with a timestamp appended is better?

Of course this is a must-have functionality.

**Comment by DallasP9124** [comment]
Is there no update to the progress (or lack of) for this?

**Comment by RMarinaro** [comment]
Is there any update for this?

**Comment by vashdev** [comment]
No update yet. 


Sent from Yahoo Mail for iPhone


On Wednesday, April 24, 2019, 4:18 PM, Ryan Marinaro <notifications@github.com> wrote:


Is there any update for this?

**Comment by qidydl** [comment]
I understand that the log stream name needs to be unique due to the token and such, but it would be helpful if that uniqueness was at the end of the name instead of the beginning, because CloudWatch only lets you filter log streams by *prefix*. It's almost impossible to find specific log streams I want to review as a result.

**Comment by klaytaybai** [comment]
Hi everyone, user-defined log stream prefixes have been added to the configs.  Using them should solve the majority of your needs, which seem to largely be filtering with CloudWatch.  If you want to see more configurations added (e.g. something involving the timestamps), please stay involved in the discussion and add GitHub reactions to the ideas you care about the most.  Thanks for the participation and feedback!

**Comment by praveenvelampudi7** [comment]
Hi,

Is there any update on being able to edit the Log stream name for Lambdas in cloud watch?

**Comment by starred-arthur** [comment]
> Hi,
> 
> Is there any update on being able to edit the Log stream name for Lambdas in CloudWatch?

Or even better, set it up in Chalice config?

**Comment by BLZB0B** [comment]
my usecase is slightly different to the above (but I think somebody highlighted something similar.

for a given app, I need to be able logs related messages to a given log stream - but that stream needs to be on a per message basis.

for example, when building a quotation in a web app, multple users are using the app simultaneously, but I'd like a stream for each user so in the event of an issue for a given user, we can follow the traces.  the stream name could be (for example) the quote number.  but it needs to be something determined at the time of writing the log, not at server / app start up.  Keeping track of existing log stream IDs shouldn't be something the consumer should need to deal with - so your previous idea of "try and write to stream ABC, if successful, good, if not, append timestamp" should handle this fine, we just need to supply the name of the stream.

Any thoughts on how to achieve this ?

thanks

**Comment by morsanu** [comment]
I also would like to have a single LogStream for each build of the app. I would like to use a build timestamp, not the default one that gets reseted any time the log is restarted.

I use log4net and only get Prefix and Suffix. I see that NLog has LogStreamName but I wouldn't change my logging library just for that. 

Any ideas?

**Comment by RomeoOni** [comment]
Hi,
@morsanu , did you arrive to find a workaround to this issue? It looks quite a long time this stands up here...

@spati2, please would it be possible to just expose a boolean parameter for the user to be able to skip the "prefix - timestamp - suffix" format? That would help a lot making NLog more flexible tool.

Many thanks!

![image](https://user-images.githubusercontent.com/61970897/107097348-0c96b900-680d-11eb-85e6-ae50c3a0c575.png)

**Comment by NelsonBN** [comment]
Is there any update for this?

**Comment by ashishdhingra** [comment]
Hi @AndrewLane,

Good morning.

Could you please check if the PR https://github.com/aws/aws-logging-dotnet/pull/84 as mentioned in https://github.com/aws/aws-logging-dotnet/issues/1#issuecomment-510661730 addresses some of the issues? This has been available in all the 3 logging libraries as per PR.

Thanks,
Ashish

**Comment by AndrewLane** [comment]
> Hi @AndrewLane,
> 
> Good morning.
> 
> Could you please check if the PR #84 as mentioned in [#1 (comment)](https://github.com/aws/aws-logging-dotnet/issues/1#issuecomment-510661730) addresses some of the issues? This has been available in all the 3 logging libraries as per PR.
> 
> Thanks,
> Ashish

I'm no longer working in this ecosystem, so I can't tell you for sure.  I looked at the PR and it looks like it provides the ability to configure a prefix.  However, if I remember correctly, my main issue was having the number of stream grow over time because a timestamp was being used as part of the stream name.  It looks like that's still the case?

**Comment by normj** [comment]
There are no plans to make the stream name configurable. The way CloudWatch Logs is designed is each process instance needs its own stream. If you want to view at the log messages in a combined view then I suggest using either CloudWatch Logs Insights or selecting all of the streams you care about and clicking the Search All button in the console.

**Comment by msegzda** [comment]
Much needed feature. Thank you!
