### ISSUE TITLE
LogStreamNameSuffix in Log4net appender not working

### ISSUE THREAD

**Issue by mdesharnais** [aws/aws-logging-dotnet#10]
There is a small problem with LogStreamNameSuffix in Log4net appender. 

It's ignored. 

![selection_031](https://cloud.githubusercontent.com/assets/28660076/26016231/33fedef6-3732-11e7-93e5-dc1210b476f7.png)

Should be : 

![image](https://cloud.githubusercontent.com/assets/28660076/26016258/503c8302-3732-11e7-8ea8-02bca27dc7d7.png)

**Comment by spati2** [comment]
Thanks for pointing this out

**Comment by spati2** [comment]
The missed property has been added

**Comment by mdesharnais** [comment]
Thanks
