### ISSUE TITLE
Set BatchPushInterval in config?

### ISSUE THREAD

**Issue by andyfurniss4** [aws/aws-logging-dotnet#104]
Is it possible to set the `BatchPushInterval` when using config values from an appsettings file? I know this can be set using the `AWSLoggerConfig` class but when passing this to `AddAWSProvider`, all the values I have in my config file are ignored.

I'm also a bit confused as to why the `AWSLoggerConfig` options don't really match what you can use in the config file. For example, you can set all of these in the config file:

```
"IncludeLogLevel": true,
"IncludeCategory": true,
"IncludeNewline": true,
"IncludeException": true,
"IncludeEventId": false,
"IncludeScopes": false,
```

...but `AWSLoggerConfig` doesn't seem to have these options.

```
public class AWSLoggerConfig : IAWSLoggerConfig
{
	public AWSLoggerConfig();
	public AWSLoggerConfig(string logGroup);

	public string LogGroup { get; set; }
	public string Profile { get; set; }
	public string ProfilesLocation { get; set; }
	public AWSCredentials Credentials { get; set; }
	public string Region { get; set; }
	public TimeSpan BatchPushInterval { get; set; }
	public int BatchSizeInBytes { get; set; }
	public int MaxQueuedMessages { get; set; }
	public string LogStreamNameSuffix { get; set; }
	public string LogStreamNamePrefix { get; set; }
	public string LibraryLogFileName { get; set; }
}
```

 I'm in a position where I need options from both methods but I can only use one or the other? Am I just missing something or is there an issue here?

**Comment by ashishdhingra** [comment]
Hi @andyfurniss4,

Thanks for posting the guidance question. After looking at the code for [ConfigurationSectionExtensions.GetAWSLoggingConfigSection](https://github.com/aws/aws-logging-dotnet/blob/f73951fc7cbed685dd5a27a8c6b8d5d04aaff521/src/AWS.Logger.AspNetCore/AWSLoggerConfigSection.cs#L29), it appears that you should be able to provide value for **BatchPushInterval** (in milliseconds as integer) if you also specify the value for "LogGroup". For example, you should be able to have configuration something like below (as from [sample code](https://github.com/aws/aws-logging-dotnet/blob/f73951fc7cbed685dd5a27a8c6b8d5d04aaff521/samples/AspNetCore/WebSample/appsettings.json#L1)):

```JSON
{
  "Logging": {
    "Region": "us-east-1",
    "LogGroup": "AspNetCore.WebSample",
    "BatchPushInterval": 2000,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "AllowedHosts": "*"
} 
```

Please let me know if this works for you.

Thanks,
Ashish
