### ISSUE TITLE
Nlog doesn't work in "Custom Runtime Function" Lambda function

### ISSUE THREAD

**Issue by max-market-engine** [aws/aws-logging-dotnet#105]
Reading from the article https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/cw-log-frameworks.html. Follow the instruction and can't make it work in my original project. So I created a simple lambda project as shown below and re-try with no luck. Please let me know if you need additional information.
Simple Lambda Function using Custom Rumtime Function Template. Runtime env is .net core 2.2
Lambda Code
```
public class Function
    {
        private static async Task Main(string[] args)
        {
            Logger logger = LogManager.GetCurrentClassLogger();
            logger.Info("Check the AWS Console CloudWatch Logs console in us-east-1");
            logger.Info("to see messages in the log streams for the");
            logger.Info("log group NLog.ConfigExample");

            Func<string, ILambdaContext, string> func = FunctionHandler;
            using (var handlerWrapper = HandlerWrapper.GetHandlerWrapper(func, new JsonSerializer()))
            using (var bootstrap = new LambdaBootstrap(handlerWrapper))
            {
                await bootstrap.RunAsync();
            }
        }

        public static string FunctionHandler(string input, ILambdaContext context)
        {
            return input?.ToUpper();
        }
    }
```
NLog.config
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwExceptions="true">
  <targets>
    <target name="aws" type="AWSTarget" logGroup="NLog.ConfigExample" region="us-east-1"/>
    <target name="logfile" xsi:type="Console" layout="${callsite} ${message}" />
  </targets>
  <rules>
    <logger name="*" minlevel="Info" writeTo="logfile,aws" />
  </rules>
</nlog>
```

**Comment by snakefoot** [comment]
You will probably have better success if you do a flush before main-exit:

`LogManager.Flush();`

You will probably have even more success if you configure NLog to write to console, and then configure the AWS-Lambda to forward the console ouput to CloudWatch.

See also: https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-cloud-logging-with-Azure-function-or-AWS-lambda

**Comment by max-market-engine** [comment]
Thanks for the quick reply.
```
LogManager.Flush();
```
Works for me to flush logs to cloud watch.
In this article https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-cloud-logging-with-Azure-function-or-AWS-lambda, the example code seems not working. It has syntax error. 

For a more complex case, for those ones who want to store logs to database or send by email, add the following code to resolve nlog service
```
var services = new ServiceCollection();
 services.AddLogging(loggingBuilder =>
            {
                // configure Logging with NLog
                loggingBuilder.ClearProviders();
                loggingBuilder.SetMinimumLevel(LogLevel.Trace);
                loggingBuilder.AddNLog();
                //your custom configuration 
                loggingBuilder.CustomNLogConfiguration();
            });

**Comment by snakefoot** [comment]
@max-market-engine You are welcome to edit the article or come with suggestions (wiki is open for editing). Never written a cloud application myself :)
