### ISSUE TITLE
Configuring ASP.NET Core Provider

### ISSUE THREAD

**Issue by tb120** [aws/aws-logging-dotnet#106]
I'm attempting to use the AWS .NET Core provider for the first time in a project. This may be (I'm sure it is actually) due to my inexperience but how do I configure the provider to allow it access to CloudWatch? I've used the Azure logging provider and it only works when the service is deployed in an App Service so there isn't any direct configuration. Do the rules for configuration of the [AWS SDK][1] apply to the provider as well? Thank you for any input and help.

[1]: https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html

**Comment by klaytaybai** [comment]
Hello @tb120.  You can find some guidance on the main README in this repo to learn how to configure the app settings.  However, I believe this [AWS developer blog](https://aws.amazon.com/blogs/developer/amazon-cloudwatch-logs-and-net-logging-frameworks) answers your question:  

> These logging plugins are all built on top of the AWS SDK for .NET, and use the same behavior used by the SDK to find AWS credentials. The credentials used by the logging plugins must have the following permissions to access CloudWatch Logs.
> 
> 
> {
>   "Version": "2012-10-17",
>   "Statement": [
>     {
>       "Effect": "Allow",
>       "Action": [
>         "logs:CreateLogGroup",
>         "logs:CreateLogStream",
>         "logs:PutLogEvents",
>         "logs:DescribeLogGroups"
>       ],
>       "Resource": [
>         "arn:aws:logs:*:*:*"
>       ]
>     }
>   ]
> }
> 
>

**Comment by tb120** [comment]
@klaytaybai Thanks for the response and thanks for pointing me to the post.
