### ISSUE TITLE
Add support for Proxy Servers

### ISSUE THREAD

**Issue by gsfataviva** [aws/aws-logging-dotnet#109]
Could you add support for proxy servers? Specifically I would like to see the following properties added to AWSLoggerCore:-

public string ProxyHost
public int ProxyPort
public string ProxyUsername
public string ProxyPassword

**Comment by klaytaybai** [comment]
Thanks for the request.  I'll see what we can do about getting it in soon.  I notice that we also had a relevant feature request a couple months back.  https://github.com/aws/aws-logging-dotnet/issues/101.

**Comment by klaytaybai** [comment]
I'll close this issue, and we'll use #101 to track it.  Note that the other issue has a workaround

**Comment by gsfataviva** [comment]
Thanks @klaytaybai
