### ISSUE TITLE
Question: Cloudwatch IAM User with Serilogs

### ISSUE THREAD

**Issue by thepersonclass** [aws/aws-logging-dotnet#110]
Hello,

I was wondering how I set the client ID and secret to log to Cloudwatch via Serilog in the config? All I see is a group and the region. Sorry I am new to logging in Cloudwatch. Any help you can give  would be appreciated!

Thanks!

**Comment by klaytaybai** [comment]
You should be able to use the Profile and ProfileLocation options as well.  If you don't specify anything related to credentials in the config, the library will use the AWS SDK for .NET's standard [fallback credentials factory](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs).  You can read more about the default process [here](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html).
