### ISSUE TITLE
.Net Core 3 support

### ISSUE THREAD

**Issue by erhanpro** [aws/aws-logging-dotnet#111]
.Net Core 3 support is critical issue

**Comment by normj** [comment]
What is not working in .NET Core 3.0?

**Comment by erhanpro** [comment]
It's installed .net core 2.1 libraries, these are unnecessary

**Comment by ashishdhingra** [comment]
Hi @erhanpro, 

Good afternoon.

I'm not sure what is the issue here or if it still exists. Please confirm if this is still an issue or if we could close it.

Thanks,
Ashish

**Comment by erhanpro** [comment]
Yes its not issue now, thank you
