### ISSUE TITLE
AWS.Logger.Serilog ignores ITextFormatter if IFormatProvider is provided.

### ISSUE THREAD

**Issue by ApocDev** [aws/aws-logging-dotnet#113]
If an IFormatProvider  is given to the sink, then the ITextFormatter is ignored entirely when rendering messages.

https://github.com/aws/aws-logging-dotnet/blob/master/src/AWS.Logger.SeriLog/AWSSink.cs#L60

This should be the opposite behavior. The IFormatProvider should be ignored in RenderLogEvent when a ITextFormatter is provided.

Repro:

```csharp
	.WriteTo.AWSSeriLog(
		new AWSLoggerConfig
		{
			...
		},
		CultureInfo.InvariantCulture, // Passing any value other than null here causes the JsonFormatter to be ignored for rendering log messages
		new JsonFormatter(null, true, CultureInfo.InvariantCulture))
```

**Comment by ashishdhingra** [comment]
Hi @ApocDev, 

Good afternoon.

Thanks for posting the issue. Looking at the [Format providers](https://github.com/serilog/serilog/wiki/Formatting-Output#format-providers) in Serilog, it appears to make more sense to consider custom `IFormatProvider` in favor of ITextFormatter, since intent might be to provide customized output. I understand  you concern, but the current implementation appears to be correct. Please let me know if this issue could be closed.

Thanks,
Ashish

**Comment by ApocDev** [comment]
I don't believe the logic here is correct. The following is what the linked method should probably be:

```csharp
        private string RenderLogEvent(LogEvent logEvent)
        { 
            if (_textFormatter != null)
            {
                using (var writer = new StringWriter(_iformatDriver ?? CultureInfo.CurrentCulture))
                {
                    _textFormatter.Format(logEvent, writer);
                    writer.Flush();
                    return writer.ToString();
                }
            }
            return logEvent.RenderMessage(_iformatDriver);
        }
```

Notice that the StringWriter takes the `_iformatDriver` provided. This allows us to specify a "culture" (or custom formatter), as well as have the logs be rendered via Json. The current logic allows either `CurrentCulture` or no custom text formatter.

**Comment by ashishdhingra** [comment]
Hi @ApocDev, 

Thanks for your input. I would discuss this with developer and let you know of any updates.

Regards,
Ashish

**Comment by ashishdhingra** [comment]
Hi @ApocDev,

Based on my discussion with developer and Serilog documentation, IFormatProvider custom implementation should take precedence over ITextFormatter. Hence closing this issue.

Thanks,
Ashish
