### ISSUE TITLE
ASP.NET Core Logging with Basic/Explicit Credentials?

### ISSUE THREAD

**Issue by karam94** [aws/aws-logging-dotnet#114]
It seems that it is not possible to explicitly inject Basic Credentials in to the AWS.Logger.AspNetCore NuGet Package.

At the moment, the only ways I've managed to get the logger to work is by:
1) Picking up my credentials within my ".aws" folder.
2) Reading credentials from my "appsettings.json" config and setting them in Environment Variables using:
`Environment.SetEnvironmentVariable("AWS_ACCESS_KEY_ID", Configuration["AWS:Access_Key"]);`

With other AWS libraries such as the SQS library, usually specifying something such as:
```
services.AddDefaultAWSOptions(new AWSOptions {
    Credentials = new BasicAWSCredentials(Configuration["AWS:Access_Key"], ...)
});
```
once, gets the job done automatically.

Is there something missing from the docs? Or is this a potential feature request?

Thanks

**Comment by klaytaybai** [comment]
Hi @karam94, thanks for the feedback.  We should make the docs clearer.  For this library, we decided not to support adding basic AWS credentials directly to the code because it is generally less secure.

You may also specify an alternative credentials file by specifying a `ProfilesLocation` other than ~/.aws/credentials.

**Comment by karam94** [comment]
> Hi @karam94, thanks for the feedback. We should make the docs clearer. For this library, we decided not to support adding basic AWS credentials directly to the code because it is generally less secure.
> 
> You may also specify an alternative credentials file by specifying a `ProfilesLocation` other than ~/.aws/credentials.

Hi @klaytaybai ,

No worries. 
I think it's probably the right decision that promotes the right practices at the end of the day :)
Look forward to seeing the updated docs.

Thanks!
