### ISSUE TITLE
Disable Colors

### ISSUE THREAD

**Issue by kbsanders** [aws/aws-logging-dotnet#116]
Is there a way to disable the ANSI escape codes used for colors in the log output?

```
2020-03-06T01:00:32.800-05:00 | [40m[32minfo[39m[22m[49m: WebApi.Controllers.TestController[0]
2020-03-06T01:00:32.801-05:00 | Testing the logger (Information)!
2020-03-06T01:00:32.801-05:00 | [40m[1m[33mwarn[39m[22m[49m: WebApi.Controllers.TestController[0]
2020-03-06T01:00:32.801-05:00 | Testing the logger (Warning)!
2020-03-06T01:00:32.801-05:00 | [41m[30mfail[39m[22m[49m: WebApi.Controllers.TestController[0]
2020-03-06T01:00:32.801-05:00 | Testing the logger (Error)!
```

**Comment by kbsanders** [comment]
**Update:**

Adding the following to my `"Logging":` settings in `appsettings.json` seems to have done the trick:

```
"Console": {
    "DisableColors": true
},
```

I had tried several other possibilities first, before opening an issue, like putting `DisableColors` directly inside of the `"Logging":` settings, and also under `"AWSProvider":` to achieve provider specific settings, but apparently it has to be under `"Console":` to work.

**Comment by normj** [comment]
This sounds like you have something configured with the console logger enabled and also anything written to the console will write to CloudWatch Logs. Fargate will do that by default write whatever is sent to the console to the CloudWatch Logs.

These libraries don't do anything with ANSI coloring. We just take the string that is app said log and push it to CloudWatch Logs.

**Comment by kbsanders** [comment]
Thank you for the response. I will look into this further. As far as I know, I'm only using the Console logger for non-production and the AWS logger for production (ECS/Fargate deployment). I achieve this using the following code in `Startup.cs`. Perhaps the Console logger is always the default, regardless of the environment.

```csharp
services.AddLogging(loggingBuilder =>
{
    if (_env.IsProduction())
    {
        loggingBuilder.AddAWSProvider(Configuration.GetAWSLoggingConfigSection());
    }
    else
    {
        loggingBuilder.AddConsole();
    }
});
```
