### ISSUE TITLE
Optionally disable library error logging

### ISSUE THREAD

**Issue by aleybe** [aws/aws-logging-dotnet#118]
Hey guys, 

I have created a PR #117 which adds a property to optionally disable the automatic logging of errors if the Library fails to log to CloudWatch (i.e the IAM credentials doesn't have access). 

The reason I have created this PR; in the past if I have used this library on a service which was running on a server and something has happened it can cause the error logs to start to fill up the installation directory. 

A better method would be to have some kind log roll-over, but I have just quickly added this boolean on/off instead. 

Let me know your thoughts. I can put a bit more time into this next week for log rollover. This is similar to an existing issue #80 and the work around was to set an empty string in the "LibraryLogFileName" property. I feel that having this additional property might be a bit more suitable as it's much clearer what it's objective is within the library. 

Looking forward to hearing from you, all feedback is welcome :) 

Thanks guys, this library is incredibly useful I appreciate all your heavy lifting :heart:

**Comment by MarcelChirtes** [comment]
Can this be resolved? was reported last year https://github.com/aws/aws-logging-dotnet/issues/80

**Comment by MarcelChirtes** [comment]
Or give an alternative if to stop it.

**Comment by MarcelChirtes** [comment]
Ok, found it, by setting LibraryLogFileName to null no log happens

**Comment by ashishdhingra** [comment]
Hi @aleybe, 

Good afternoon.

Please confirm if the workaround provided by @MarcelChirtes works for you.

Thanks,
Ashish

**Comment by aleybe** [comment]
hi @ashishdhingra this can be closed, it was more or less an issue to address the PR #117 
just some additional functionality to make the user experience a little friendlier :)

Thanks,
Alex
