### ISSUE TITLE
System.ArgumentException : Target cannot be found: 'AWSTarget'

### ISSUE THREAD

**Issue by chinaniit** [aws/aws-logging-dotnet#12]
I'm write a test project invoke NLog library with aws, but throw:
System.ArgumentException : Target cannot be found: 'AWSTarget'
----------------------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwExceptions="true">
  <targets>
    <target xsi:type="File"
            footer =""
            name="f"
            encoding="utf-8"
            fileName="${basedir}/Logs/${shortdate}.log"
            archiveFileName="${basedir}/Logs/${shortdate}.{#####}.log"
            archiveAboveSize="1024"
            archiveNumbering="Sequence"
            concurrentWrites="true"
            keepFileOpen="false"
            layout="${longdate} ${uppercase:${level}} ${message} ${newline}"/>
    <target name="aws" type="AWSTarget" logGroup="Test" region="us-east-2"/>
    </targets>
  <rules>
    <logger name="*" minlevel="Error" writeTo="f, aws" />
  </rules>
</nlog>

**Comment by chinaniit** [comment]
install-package AWS.Logger.Core resolved.

**Comment by spati2** [comment]
Hi @chinaniit , are you using the latest AWS.Logger.NLog version 1.1.1? If so, this issue would have been resolved. Let me know if error persists even after installing the new package

**Comment by tankthomas** [comment]
Hi, I'm using the AWS.Logger.NLog and the issue still exist.

**Comment by bobbanks** [comment]
I'm having a similar issue.  1.1.1 of AWS.Logger.NLog and AWS.Logger.Core.

**Comment by bobbanks** [comment]
Everything works as expected if I configure programmatically.

**Comment by bobbanks** [comment]
Resolved by adding 

`  <extensions>
    <add assembly="NLog.AWS.Logger" />
  </extensions>`

**Comment by SashaKazyrevich** [comment]
As per https://github.com/NLog/NLog.Extensions.Logging/issues/155#issuecomment-337182476 we should use NLog 4.5 with .NET Core 2.0 ("...NLog 4 and 5 aren't binary compatible. You should use 4.5 indeed for .NET Core 2...")

I'm trying to setup logging to CloudWatch with NLog from .NET Core 2.0 - looks like there's no AWS.Logger.NLog which targets NLog 4.5 

There's AWS.Logger.NLog v1.1.1 which targets NLog 5.0, and if I use AWS.Logger.NLog v1.1.0 there's an error 

Type load exception. Exception: System.TypeLoadException: Method 'get_LibraryLogFileName' in type 'NLog.AWS.Logger.AWSTarget' from assembly 'NLog.AWS.Logger, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604' does not have an implementation.

My csproj references:
  <ItemGroup>
    <PackageReference Include="AWS.Logger.Core" Version="1.1.3" />
    <PackageReference Include="AWS.Logger.NLog" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.0.0" />
    <PackageReference Include="NLog" Version="4.5.0-rc01" />
    <PackageReference Include="NLog.Extensions.Logging" Version="1.0.0-rtm-rc2" />
  </ItemGroup>

**Comment by azaytsev-csr** [comment]
@SashaKazyrevich have you ever solved this? having the same issue

**Comment by sakthiwhale** [comment]
as bobbanks mentioned, I fixed this error by adding the below to the nlog.config file
``` 
<extensions>
    <add assembly="NLog.AWS.Logger"/>
</extensions>
```
