### ISSUE TITLE
ASPNETCORE 3.1 improperly formatted logs

### ISSUE THREAD

**Issue by gitisz** [aws/aws-logging-dotnet#120]
I recently upgraded to dotnetcore 3.1 from 2.2 and also upgraded this aws-logging-dotnet to`<PackageReference Include="AWS.Logger.AspNetCore" Version="2.2.0" />`.  After deploying to AWS, I see the CloudWatch logs in my log group are all clubbed together into one log stream.  This makes using Insights fail to find logs.

Here is a sample of logs in CW after upgrading:

```
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'test.Api.Controllers.HealthController.Get (Test.Api)'
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.3621ms 200 application/json; charset=utf-8
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://qa-e-one-hub-service.clouddqt.capitalone.com/one/failovergroup/getall application/json 
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'test.Api.Controllers.FailoverGroupController.GetAll (Test.Api)'
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "GetAll", controller = "FailoverGroup"}. Executing controller action with signature test.Models.FailoverGroupResponse GetAll() on controller test.Api.Controllers.FailoverGroupController (Test.Api).
```

If it helps, here is the Startup.cs code which I am using to wire up configuration:

```
        public void Configure(IApplicationBuilder app,
            IWebHostEnvironment env,
            IServiceProvider serviceProvider,
            ILoggerFactory loggerFactory,
            IHostApplicationLifetime lte,
            IDistributedCache cache
            )
        {
            app.UseDefaultFiles();
            app.UseStaticFiles();
            app.UseRouting();

            var awsLogConfiguration = this.Configuration.GetAWSLoggingConfigSection();

            if (awsLogConfiguration != null)
            {
                awsLogConfiguration.Config.LogStreamNameSuffix = $"{System.Net.Dns.GetHostName()}";
                loggerFactory.AddAWSProvider(Configuration.GetAWSLoggingConfigSection(),
                    formatter: (logLevel, message, exception) =>
                        $"[{DateTime.Now} {logLevel} {message} {exception?.Message} {exception?.StackTrace}]");

            }
        }
```

... and finally the configuration for the environment as defined in Appsettings.json:

```
,
  "Logging": {
    "Region": "us-east-1",
    "LogGroup": "test-stack-qa",
    "IncludeLogLevel": true,
    "IncludeCategory": true,
    "IncludeNewline": true,
    "IncludeException": true,
    "IncludeEventId": false,
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Debug",
      "Microsoft": "Information",
      "Microsoft.AspNetCore.SignalR": "Warning",
      "Microsoft.AspNetCore.Http.Connections": "Warning"
    }
  }
```

Based on additional digging, some have suggested using a formatter, and formatting the output to JSON, however I am not able to find an adequate example that demonstrates proper serialization.  

Shouldn't this package emit properly formatted logs to CW as a default?

**Comment by gitisz** [comment]
Circling back on this, I believe the behavior where logs were getting clubbed together in a single stream was likely due to a log format change between framework 2.2 and 3.1.  

I was never able to get logs to stream to CW using this package, so I abandoned the effort.  What did work for me was:

- Change to adding awslogs driver as part of my TaskDefinition (using ECS)

 - try and ultimately switch to Serilog
 - update `awslogs-datetime-format` to match the timestamp of my logs
 - update startup to inject Serilog into constructors based on Serilog config in appsettings.json

Relevant examples:
Task Definition (assumes cluster has awslogs driver installed):
```
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref 'AWS::StackName'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Ref Name
              awslogs-datetime-format: '%m/%d/%Y %H:%M:%S'
```
Startup.cs
```
        public void ConfigureServices(IServiceCollection services)
        {
...
            Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(this.Configuration)
                .Enrich.FromLogContext()
                .CreateLogger();
            AppDomain.CurrentDomain.ProcessExit += (s, e) => Log.CloseAndFlush();
            services.AddSingleton<ILogger>(Log.Logger);
            services.AddLogging(logging =>
            {
                logging.AddSerilog(Log.Logger);
            });
       }
```

Appsettings.json
```
  ... 

  "Serilog": {
    "Using": [
      "Serilog.Sinks.Console"
    ],
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "outputTemplate": "[{Timestamp} {Level:u}] {Message:lj} {Properties:j}{NewLine}{Exception}"
        }
      }
    ]
  }
```
This solution uses the console out to write logs, and so may not be desirable for some users.  It might also be that streaming logs to CW using this aws-logging-dotnet package may have required additional proxy settings to work properly, however I didn't find a method to set these values.

**Comment by klaytaybai** [comment]
Thanks for the update.  I'll respond to this more soon after trying to reproduce it.

**Comment by madmox** [comment]
Having the same issue here. Logs are very difficult to analyse now. Relevant code in my application:

Startup.cs:
```
public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
{
    IConfigurationSection loggingConfig = this._config.GetSection("Logging");
    loggerFactory.AddLambdaLogger(options: loggingConfig.GetLambdaLoggerOptions());
    ...
}
```

appsettings.json:
```
{
    ...
  "Logging": {
    "LogLevel": {
      "Default": "Information"
    },
    "Lambda.Logging": {
      "IncludeCategory": true,
      "IncludeLogLevel": true,
      "IncludeNewline": true,
      "IncludeException": true,
      "IncludeEventId": true,
      "IncludeScopes": true
    }
  }
}
```

Resulting logs:
```
// console logger log entries (color codes, 1 entry per line, logger index appended to logger name...)
2020-08-31T17:58:44.505Z [40m[32minfo[39m[22m[49m: My.Service[0]
2020-08-31T17:58:44.505Z test log entry

// followed by the lambda logger log entry
2020-08-31T17:58:44.505Z [Information] My.Service: test log entry
```

Logs are duplicated: 1 entry formatted correctly (lambda logger), 1 entry with color codes (console logger). It looks like the console logger is added by default by `APIGatewayProxyFunction`. Calling `ILoggingBuilder.ClearProviders()` in `APIGatewayProxyFunction.Init` does not help, it disables both loggers, even if I add lambda logger after that :/

**Comment by ashishdhingra** [comment]
Hi @gitisz, 

Good afternoon.

Could you please help elaborate the issue in the following format with correct expected output versus current  output (if possible, also the CloudWatch screenshots):



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

This would enable us to troubleshoot the issue better.

Thanks,
Ashish
