### ISSUE TITLE
AWS Log4net appender  doesn't alert to AWS cloudwatch 

### ISSUE THREAD

**Issue by goonux** [aws/aws-logging-dotnet#121]
I have a .Net Framework project with Log4net framework used already.  (I have appended the output logs to local file and to remote system log, these things are working fine). 

Now I want to add additional appender AWS.Logger.Log4net  to push the logs to AWS cloudwatch. 

I have installed all Nuget packages dependence below:
`<package id="AWS.Logger.Core" version="1.6.0" targetFramework="net472" />
<package id="AWS.Logger.Log4net" version="1.5.2" targetFramework="net472" />
<package id="AWSSDK.CloudWatchLogs" version="3.3.100.39" targetFramework="net472" /
<package id="AWSSDK.Core" version="3.3.103.2" targetFramework="net472" />`

Then, I added the additional appender code below into my App.config file. 

`<log4net>
  ....
  <appender name="AWS" type="AWS.Logger.Log4net.AWSAppender,AWS.Logger.Log4net">
      <accessKeyId>MY_ACCESS_KEY</accessKeyId>
      <secretKey>MY_SCRETKEY</secretKey>
      <LogGroup>Log4net.ConfigExample</LogGroup>
      <Region>us-west-2</Region>
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%-4timestamp [%thread] %-5level %logger %ndc - %message%newline" />
    </layout>
  </appender>
 .....
  <root>
    <level value="DEBUG" />
    <appender-ref ref="AWS" />
    ..........
  </root>
</log4net>`

But, there is nothing happens, So the question is may I missing some configuration?
Or my settings above is not right? 
So please help me out.

**Comment by ashishdhingra** [comment]
Hi @goonux, 

Thanks for posting the question. Please check if you have setup AWS credentials in the credentials store or not. Looking at the code for [AWSLoggerConfig](https://github.com/aws/aws-logging-dotnet/blob/f73951fc7cbed685dd5a27a8c6b8d5d04aaff521/src/AWS.Logger.Core/AWSLoggerConfig.cs#L18), it appears that the elements _<accessKeyId>_ and _<secretKey>_ are not read from App.config.

Please let me know if this provides some guidance.

Thanks,
Ashish
