### ISSUE TITLE
NLog.Web.ASPNetCore: Log group created but no entries

### ISSUE THREAD

**Issue by Donavan** [aws/aws-logging-dotnet#122]
I've added an AWS target to an existing NLog configuration.  The log groups get created on startup, and a log stream exists with the correct prefix and suffix, however they're completely empty.

Pulling the same code and running in a console test app using just plain Nlog. Works as expected.

Is there any  sort of diagnostic console output I could enable to try and diagnose this?

**Comment by classifieds-dev** [comment]
I'm having the same issue. I've used a variety of different configurations. I have been able to populate the created log stream(s) with events. I've used the following configurations:

- Default logger in aws-lambda-dotnet
- .NET Core 3 logger in this package.
- Serilog AWS sink.

The lambda which is being tested is associated with a role that has a policy containing permissions to read and write cloud watch log streams, and events. The role also can be assumed by the lambda service.

When the lambda is tested in the lambda testing console the log entries are written and clearly visible. However, the log entries are not being persisted to the associated cloud watch stream.

**Comment by snakefoot** [comment]
@Donavan When using NLog, then you can enable the NLog InternalLogger to see exception-output from AWS-engine.

https://github.com/NLog/NLog/wiki/Internal-Logging

**Comment by ashishdhingra** [comment]
Hi @Donavan,

Good afternoon.

Please let me know your use case and which logger specified in [aws-logging-dotnet](https://github.com/aws/aws-logging-dotnet) repository are you using.

Also, for Lambda, as mentioned on the repository page, it is recommended to use either the ILambdaContext.Logger.LogLine or the Amazon.Lambda.Logging.AspNetCore package.

Thanks,
Ashish
