### ISSUE TITLE
AWS.Logger.AspNetCore not creating logs in cloudwatch

### ISSUE THREAD

**Issue by faizaaniesta** [aws/aws-logging-dotnet#123]
I want to log request and response to and from my .NET Core APIs using AWS .NET Logger and Cloudwatch. My .NET Core app is deployed using Elastic Beanstalk. I have installed the AWS.Logger.AspNetCore package and setup the logger as follows in my StartUp.cs
```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory) {
    loggerFactory.AddAWSProvider(Configuration.GetAWSLoggingConfigSection());
    //Some more configuration related to the app.
}
```
In my appsettings.json I have the following configuration:
```
"AWS.Logging": {
  "Region": "us-east-2",
  "LogGroup": "MyAppLogs",
  "LogLevel": {
    "Default": "Debug",
    "System": "Information",
    "Microsoft": "Information"
  }
}
```
I have also attached the appropriate policies to my Elastic Beanstalk role to create, update and get log groups and streams. This configuration works properly when working locally (within Visual Studio) but when it is deployed empty logs are created on Cloudwatch.

**Comment by epatrick** [comment]
I have the same issue - any luck troubleshooting?

**Comment by ashishdhingra** [comment]
Hi @faizaaniesta,

Thanks for posting a guidance question. I used the ASP.NET Core logging [WebSample](https://github.com/aws/aws-logging-dotnet/blob/master/samples/AspNetCore/WebSample) sample in [aws-logging-dotnet](https://github.com/aws/aws-logging-dotnet) (with minimal tweak to remove reference to AWS.Logger.AspNetCore.csproj and install AWS.Logger.AspNetCore Nuget Package) and was successfully able to push logs into CloudWatch for ASP.NET Core application deployed using Elastic Beanstalk.

Few things to note for enabling Cloudwatch Logs for application deployed using Elastic Beanstalk:

1. Following policy needs to be attached to “**aws-elasticbeanstalk-ec2-role”**.

```JSON
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "CloudWatchLogsAccess",
            "Action": [
                "logs:CreateExportTask",
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:DescribeDestinations",
                "logs:DescribeExportTasks",
                "logs:DescribeLogGroups",
                "logs:FilterLogEvents",
                "logs:PutDestination",
                "logs:PutDestinationPolicy",
                "logs:PutLogEvents",
                "logs:PutMetricFilter"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:logs:*:*:log-group:*"
            ]
        }
    ]
}
```

2. CloudStream on the Elastic Beanstalk application needs to be enabled. This could be done using Edit Software Configuration in the Configuration Menu for the Elastic Beanstalk application.

Please verify the above for your application and let me know if it works.

Thanks,
Ashish

**Comment by faizaaniesta** [comment]
Hi, I performed your recommendations while I was hooking up AWS.Logger.AspNetCore with my app but to no avail. I eventually moved to Serilog.
