### ISSUE TITLE
not sending logs over to cloudwatch

### ISSUE THREAD

**Issue by tankthomas** [aws/aws-logging-dotnet#13]
So, I was following the examples and setting up log4net/cloudwatch. But somehow it's not sending logs to cloudwatch. My settings are like this:

![cloudwatch1](https://cloud.githubusercontent.com/assets/6215939/26514537/a6e04e70-422f-11e7-8481-c4e1313844fd.png)

initiated in global.asax
![cloudwatch2](https://cloud.githubusercontent.com/assets/6215939/26514535/a6dcf3e2-422f-11e7-904d-8a65b656c1d7.png)

then send exceptions over
![cloudwatch3](https://cloud.githubusercontent.com/assets/6215939/26514536/a6de89d2-422f-11e7-9c4c-2bad4a1d1286.png)

anyone knows why?

Really appreciate the time and effort of whoever look into this issue.

**Comment by spati2** [comment]
Can you try by explicitly specifying the log4net.config in the XmlConfigurator.config as such ?
XmlConfigurator.Configure(FileInfo configFile);

**Comment by spati2** [comment]
Closing issue after a 7 day inactive period
