### ISSUE TITLE
Support for AWSSDK.Core 3.5?

### ISSUE THREAD

**Issue by winzig** [aws/aws-logging-dotnet#136]
Trying to incorporate this with AWSSDK.Core 3.5:

```
<PackageReference Include="AWS.Logger.AspNetCore" Version="2.2.0"/>
```

Getting this error:

>warning NU1608: Detected package version outside of dependency constraint: AWSSDK.CloudWatchLogs 3.3.100.39 requires AWSSDK.Core (>= 3.3.103.2 && < 3.4.0) but version AWSSDK.Core 3.5.1.5 was resolved.

Any ETA on support for AWSSDK.Core 3.5? Or is there a workaround that I'm missing? Thanks!

**Comment by ashishdhingra** [comment]
Hi @winzig, 

Thanks for reporting the issue. I will discuss this issue with the development team and hopefully we could get an update soon.

Thanks,
Ashish

**Comment by iofluxdev1** [comment]
Would love for this package to support AWSSDK.Core 3.5 as I had to remove it, because it kept us from upgrading other dependencies with new functionality that used version 3.5+ of the AWS SDK.

**Comment by bravecobra** [comment]
I just hit the same issue. Updating to the latest AWSSDK.Core would seems very nice at this point. Would you like a PR for this or do you guys have this covered?

**Comment by thomasd3** [comment]
same here, that would be a very welcome update.

**Comment by thomasd3** [comment]
is there any word on this? I'm in a position where I need tell the others if we will use this package (if it will be updated for sure) and I'm curious where this would fit in the priority list.

**Comment by bravecobra** [comment]
I guess/hope the only way to speed things up is to add a PR

**Comment by thomasd3** [comment]
I haven't looked at the code yet; is the AWSSDK's new version API different? or we're talking about minor changes?

**Comment by iofluxdev1** [comment]
> I haven't looked at the code yet; is the AWSSDK's new version API different? or we're talking about minor changes?

Minor as far as I can tell.

**Comment by jstallm** [comment]
Recently after trying to update some nuget packages, I noticed a compilation warning message
`warning NU1608: Detected package version outside of dependency constraint: AWSSDK.S3 3.3.111.9 requires AWSSDK.Core (>= 3.3.107.8 && < 3.4.0) but version AWSSDK.Core 3.5.1.32 was resolved
`
Is this warning message related to above? What is also interested is that I am not even referencing directly AWSSDK.S3 3.**3.111.9**. A separate project is instead referencing AWSSDK.S3 3.**5.3.10**

What are my options here? Here is my best guess
A. Ignore warning
B. Revert nuget package update
C. Other


Please let me know if this is related as appears to be. Thank you.

**Comment by hunanniu** [comment]
This should be resolved now

**Comment by ValeryYegorov** [comment]
I see same issue using XRay
````
Warning	NU1608	Detected package version outside of dependency constraint: AWSSDK.XRay 3.3.3 requires AWSSDK.Core (>= 3.3.25.1 && < 3.4.0) but version AWSSDK.Core 3.5.1.40 was resolved.		
````

**Comment by ashishdhingra** [comment]
@ValeryYegorov Request you to please open a new issue in the main aws-sdk-net repository.
