### ISSUE TITLE
Update release notes to explain major version bump

### ISSUE THREAD

**Issue by cfbao** [aws/aws-logging-dotnet#143]
There's nothing in the release notes on the major version bump that happened last month in #140.

Because it's a major version bump, I was looking for notes on possible breaking changes when dependabot wanted to update our packages, but couldn't find any. I had to dig through list of PRs to find what actually changed, but it shouldn't be necessary.

**Comment by ashishdhingra** [comment]
Hi @cfbao,

Good morning.

Please advise if your are referring to https://github.com/aws/aws-logging-dotnet/blob/master/RELEASE.CHANGELOG.md to be updated or something else. I do see comment in the PR about change description.

Thanks,
Ashish

**Comment by cfbao** [comment]
Yes, I'm referring to https://github.com/aws/aws-logging-dotnet/blob/master/RELEASE.CHANGELOG.md.
My point being users like me shouldn't have to look up merged PRs to find change descriptions.

**Comment by ashishdhingra** [comment]
Hi @cfbao,

The https://github.com/aws/aws-logging-dotnet/blob/master/RELEASE.CHANGELOG.md has been updated. Hence closing this issue.

Thanks,
Ashish
