### ISSUE TITLE
EC2 Instance Id Layout Renderer

### ISSUE THREAD

**Issue by gjdownes** [aws/aws-logging-dotnet#144]
I've been using the `${machinename}` renderer to identify the origin machine of log data, but I'm wondering if there's a way to include the instance id instead since there are cases in my environment where the machine name can be duplicated.

I see this information is available in the EC2InstanceMetadata utility:
https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Util/TEC2InstanceMetadata.html

**Comment by ashishdhingra** [comment]
Hi @gjdownes,

Good morning.

Please share your use case where you are logging `${machinename}` and instead trying to log `instanceid`. Does `EC2InstanceMetadata.InstanceId` call not work since this is a static class?

Thanks,
Ashish

Thanks,
Ashish

**Comment by gjdownes** [comment]
Hi Ashish,

I have several EC2 instances sending log data to CloudWatch. I use the ${machinename} to determine which instance errors originate from, e.g.:

```
2020-11-18 10:00:01 ERROR **AWS-EC2-01** <message>
2020-11-18 10:00:02 ERROR **AWS-EC2-03** <message>
```

where AWS-EC2-01 and AWS-EC2-03 are different EC2 instances.

The problem is if a node is spawned from an AMI image, the machine name does not change, so I can't reliably identify the instance with this renderer.

I'm hoping I could instead use the instance ID which should always be unique per server. 

After having a closer look at the NLog docs, I might be able to create a custom layout renderer if this functionality isn't available out-of-the-box.

Thanks,
Graeme
