### ISSUE TITLE
 AWS.Logger.Nlog > Internal log file grows huge and causes full disks.

### ISSUE THREAD

**Issue by egeaydin** [aws/aws-logging-dotnet#146]
Hello all,

AWS CloudWatch was down for a few hours about two weeks ago, and my services started generating internal log files when sending the logs to CloudWatch. However, these files grew huge and caused our instance's disks to be full. I was wondering if there is a way to configure the internal logging to have rotating functionality or limit the file size. If not, how do you disable the internal logging for AWS.Logger.Nlog all together? 

Thanks in advance

**Comment by ashishdhingra** [comment]
Hi @egeaydin,

Good evening.

Similar issue https://github.com/aws/aws-logging-dotnet/issues/145 was logged few days back where internal log file `aws-logger-errors.txt` was growing in size.

If you are using `NLog.config` to load configuration, you could try disabling logging to the file `aws-logger-errors.txt` by setting `LibraryLogFileName` to **empty** string in `NLog.config` (example below).

```XML
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwConfigExceptions="true">
	<extensions>
		<add assembly="NLog.AWS.Logger" />
	</extensions>
	<targets>
		<target name="aws" type="AWSTarget" logGroup="NLog.ConfigExample" region="us-east-1" LibraryLogFileName=""/>
	</targets>
	<rules>
		<logger name="*" minlevel="Info" writeTo="aws" />
	</rules>
</nlog>
```

If you are configuring NLog programmatically, then following code (as an example) could be used which sets `AWSTarget.LibraryLogFileName` to `null`:
```C#
var config = new LoggingConfiguration();

var consoleTarget = new ColoredConsoleTarget();
config.AddTarget("console", consoleTarget);

var awsTarget = new AWSTarget()
{
     LogGroup = "NLog.ProgrammaticConfigurationExample",
     Region = "us-east-1"
 };
awsTarget.LibraryLogFileName = null;
config.AddTarget("aws", awsTarget);

config.LoggingRules.Add(new LoggingRule("*", LogLevel.Debug, consoleTarget));
config.LoggingRules.Add(new LoggingRule("*", LogLevel.Debug, awsTarget));

LogManager.Configuration = config;
```

Hope this helps. Please let me know if this works. If yes, kindly confirm if this issue could be closed.

Thanks,
Ashish

**Comment by egeaydin** [comment]
Hi Ashish, thank you so much for your answer. 

I was wondering is there a way to disable this LibraryLogFileName  for **all** the targets that are defined in the **NLog.config** file? I have a couple of targets for each of my projects. And I could easily forget making libraryLogFileName null for them.

**Comment by ashishdhingra** [comment]
Hi egeaydin,

It's only applicable for **AWSTarget**. Hope this helps. Please let me know if this issue could be closed if your problem is resolved.

Thanks,
Ashish

**Comment by egeaydin** [comment]
What do you mean? I didn't mention any other targer.

**Comment by ashishdhingra** [comment]
> What do you mean? I didn't mention any other targets.
> 
> **Edit**:
> I understand the confusion, I meant all AWSTargets.

Yes, the `LibraryLogFileName` is only applicable for `AWSTarget`(s). Looks the you have configured `AWSTarget` in `NLog.config` and setting `LibraryLogFileName` to `null`. In such a scenario, reload the configuration to take it to effect, refer code in https://github.com/aws/aws-logging-dotnet/issues/131#issuecomment-696298470.

Is there a reason of not setting `LibraryLogFileName` to empty string in `NLog.config`?

Thanks,
Ashish

**Comment by egeaydin** [comment]
The reason I prefer to this way is so I have this as default behaviour and so I don't have to worry about setting it in the config file in case I forgot to do so. 

This is the code I call at the beginning of the application. 

` var config = NLog.LogManager.Configuration;

var awsTargets = NLog.LogManager.Configuration.AllTargets.Where(t => t is AWSTarget).Select(t => (AWSTarget)t);

foreach (var target in awsTargets)
{
    target.LibraryLogFileName = null;
}

NLog.LogManager.Configuration = config;

NLog.LogManager.ReconfigExistingLoggers(); `

But the very first time you log something, it still generates aws-logger-errors.txt with one entry:

> Log Entry :
12/15/2020 1:17:56 PM
:
:System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken) at Amazon.Runtime.Internal.HttpHandler1.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)

After that, It doesn't log the errors as expected. However, I would rather aws-logger-errors.txt not being generated at all.

**Comment by ashishdhingra** [comment]
Hi @egeaydin,

If you are using simple console application, then this should not generate log file if this configuration is done in the beginning. For ASP.NET applications, the point where you would need to initialize this might be different than simple console application. You might refer Microsoft's/NLog documentation for appropriate point in pipeline where this configuration changes could be made before it gets a chance to log to CloudWatch.

I'm not sure what further guidance could be provided here since above are the only options to disable log file generation.

Thanks,
Ashish

**Comment by egeaydin** [comment]
I do it in a console application and it still happens. I haven't tried an ASP.NET application.

**Comment by ashishdhingra** [comment]
> I do it in a console application and it still happens. I haven't tried an ASP.NET application.

So it looks like NLog configuration is loaded at program load for which we might not have control. You might try moving your logic to program constructor. I would also advise checking NLog/Microsoft's documentation if there is some hook or place, where we could control the configuration load.

Thanks,
Ashish

**Comment by egeaydin** [comment]
I don't think you are getting the issue fully. It actually works in a sense. Besides the fact that the 'aws-logger-errors.txt' being generated with a single entry of "Task cancelled exception" no other error from the library is logged. So it **works**; the only problem is that the Task cancelled exception when you call logger the very first time.

**Comment by snakefoot** [comment]
@egeaydin Any reason for doing this funny hack with assigning LibraryLogFileName at runtime after having loaded NLog-Configuration. Instead of jus updating your NLog.config ? (Then you will not get the "Task cancelled exception" )

**Comment by egeaydin** [comment]
@snakefoot  I answered this twice already but here:
The reason I prefer this way is so I have this as default behavior and so I don't have to worry about setting it in the config file in case I forgot to do so. I could make it so this code is called in all my applications from my utility library.

**Comment by snakefoot** [comment]
I agree that having to explicit disable `LibraryLogFileName` is a bad default for a library. Debug-logging should be something you activate when you are troubleshooting. Not something that is always enabled.

But it is just a matter of creating a pull-request, to get a better default-behavior.

**Comment by ashishdhingra** [comment]
> I don't think you are getting the issue fully. It actually works in a sense. Besides the fact that the 'aws-logger-errors.txt' being generated with a single entry of "Task cancelled exception" no other error from the library is logged. So it **works**; the only problem is that the Task cancelled exception when you call logger the very first time.

I get it, but the fact that `aws-logger-errors.txt` is generated means that the configuration changes were applied, the configuration reloaded and some other initialization task was cancelled due to reload, which logs the error in the previous thread. I'm not sure how this could be controlled and as mentioned in my previous comment, you might check NLog/Microsoft's documentation on how to control configuration load at startup (may be when NLog library is loaded it looks for the config file, can we control it, etc.).

As @snakefoot mentioned, feel free to create a new `feature-request` issue along with PR, development team would review it and come back to you with review comments (if any). 

Thanks,
Ashish

**Comment by egeaydin** [comment]
@snakefoot I wasn't complaining about anything just trying to see if there is something better I could do. 

@ashishdhingra thank you for all your help. I think the issue can be closed!
