### ISSUE TITLE
.NET AWS LambdaEntryPoint, IWebHostBuilder .UseNLog not working

### ISSUE THREAD

**Issue by suresh-hautelook** [aws/aws-logging-dotnet#148]
.net core 3.1
Using AWS Serverless Lambda template.

Logging to NLog works only from LocalEntryPoint, but not from LambdaEntryPoint. 

```C#
 public class LambdaEntryPoint : Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction
    {
        protected override void Init(IWebHostBuilder builder)
        {
            var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();
            try
            {
                logger.Info("INVENTORY INGESTION LAMBDA FUNCTION - Init WebHost");

                builder.UseStartup<Startup>()
						.ConfigureLogging((ctx, logging) =>
						{
							logging.ClearProviders();
							logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
						}).UseNLog();
            }
            catch (Exception ex)
            {
                logger.Error(ex, $"{typeof(LocalEntryPoint).FullName} stopped becuase of exception.");
            }
            finally
            {
                NLog.LogManager.Shutdown();
                LogManager.Flush(new TimeSpan(0, 0, 3));
            }
        }
}
```
```C#
    [Route("api/[controller]")]
    public class InventoryController : ControllerBase
    {
        private readonly ILogger<InventoryController> _logger;

        public InventoryController(ILogger<InventoryController> logger)
        {
            _logger = logger;
        }
        // GET api/inventory
        [HttpGet]
        public IEnumerable<string> Get()
        {
			_logger.LogDebug("INVENTORY INGESTION Request received. Route: {endpointName}, Method: {method}", "api/inventory", "GET");
			_logger.LogInformation("INVENTORY INGESTION Request received. Route: {endpointName}, Method: {method}", "api/inventory", "GET");

            var environment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
            return new string[] { environment, $"{DateTime.UtcNow.ToString()}" };
        }
}
```

### Environment

* Build Version: 
* OS Info: 
* Build Environment: 
* Targeted .NET Platform:  

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @suresh-hautelook,

Good afternoon.

Could you please check/share the following:
- Are your executing the Lambda Test Tool to test `LambdaEntryPoint`? Or, the issue happens after deploying to AWS Lambda environment?
- Lambda has appropriate permissions to log to CloudWatch Logs.
- Share the CloudWatch Logs.
- Share the 'NLog.config'
- Check whether NLog.config has `AWSTarget` (refer https://github.com/aws/aws-logging-dotnet/blob/master/samples/NLog/ConfigExample/NLog.config as an example)

Thanks,
Ashish

**Comment by suresh-hautelook** [comment]
Hi @ashishdhingra 

Are your executing the Lambda Test Tool to test LambdaEntryPoint? Or, the issue happens after deploying to AWS Lambda environment?
>> Issue happens after deploying to AWS lambda environment.

Lambda has appropriate permissions to log to CloudWatch Logs.
Share the CloudWatch Logs.
>> I'm trying to send logs to Splunk cloud. (nuget: NLog.Targets.Splunk)

Share the NLog.config
>>
`
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Info"
      internalLogFile="c:\temp\internal-nlog.txt">

	
	<extensions>
		<add assembly="NLog.Web.AspNetCore"/>
	</extensions>

	
	<targets async="true">
		
		

		
		

		<target name="Splunk"
		        xsi:type="SplunkHttpEventCollector"
		        serverUrl="https://xyz.splunkcloud.com"
		        token="xyz"
		        channel="78a3e028-95cd-44b7-b8ba-c40bb5b3216f"
		        retriesOnError="0"
		        batchSizeBytes="0"
		        batchSizeCount="0"
		        includeEventProperties="true"
		        includeMdlc="false"
		        includePositionalParameters="false"
		        MaxConnectionsPerServer="10"
		        IgnoreSslErrors="true">
			<contextproperty name="host" layout="${machinename}" />
			<contextproperty name="threadid" layout="${threadid}" />
			<contextproperty name="logger" layout="${logger}" />
		</target>
	</targets>

	
	<rules>
		
		

		
		<logger name="Microsoft.*" maxlevel="Info" final="true" />

		<logger name="*" minlevel="Debug" writeTo="Splunk" />

		
		
	</rules>
</nlog>
`


Check whether NLog.config has AWSTarget (refer https://github.com/aws/aws-logging-dotnet/blob/master/samples/NLog/ConfigExample/NLog.config as an example)
>> As i'm not trying to send logs to cloudwatch. I hope this is not necessary.
However I have splunk target registered.

**Comment by ashishdhingra** [comment]
> Hi @ashishdhingra, please check my answers below.
> 
> Are your executing the Lambda Test Tool to test LambdaEntryPoint? Or, the issue happens after deploying to AWS Lambda environment?
> 
> > > Issue happens after deploying to AWS lambda environment.
> 
> Lambda has appropriate permissions to log to CloudWatch Logs.
> Share the CloudWatch Logs.
> 
> > > I'm trying to send logs to Splunk cloud. (nuget: NLog.Targets.Splunk)
> 
> Share the NLog.config
> 
> > >
> 
> `
> 
> ```
> 
> <extensions>
> 	<add assembly="NLog.Web.AspNetCore"/>
> </extensions>
> 
> 
> <targets async="true">
> 	
> 	
> 
> 	
> 	
> 
> 	<target name="Splunk"
> 	        xsi:type="SplunkHttpEventCollector"
> 	        serverUrl="https://xyz.splunkcloud.com"
> 	        token="xyz"
> 	        channel="78a3e028-95cd-44b7-b8ba-c40bb5b3216f"
> 	        retriesOnError="0"
> 	        batchSizeBytes="0"
> 	        batchSizeCount="0"
> 	        includeEventProperties="true"
> 	        includeMdlc="false"
> 	        includePositionalParameters="false"
> 	        MaxConnectionsPerServer="10"
> 	        IgnoreSslErrors="true">
> 		<contextproperty name="host" layout="${machinename}" />
> 		<contextproperty name="threadid" layout="${threadid}" />
> 		<contextproperty name="logger" layout="${logger}" />
> 	</target>
> </targets>
> 
> 
> <rules>
> 	
> 	
> 
> 	
> 	<logger name="Microsoft.*" maxlevel="Info" final="true" />
> 
> 	<logger name="*" minlevel="Debug" writeTo="Splunk" />
> 
> 	
> 	
> </rules>
> ```
> 
> `
> Check whether NLog.config has AWSTarget (refer https://github.com/aws/aws-logging-dotnet/blob/master/samples/NLog/ConfigExample/NLog.config as an example)
> 
> > > As i'm not trying to send logs to cloudwatch. I hope this is not necessary.
> > > However I have splunk target registered.

Hi @suresh-hautelook,

Since you are sending logs to non-AWS service, I think you might need to configure VPC. 
<img width="1509" alt="Screen Shot 2021-01-08 at 6 25 57 PM" src="https://user-images.githubusercontent.com/67916761/104080888-cc2d2680-51df-11eb-9ecb-913a77d14f09.png">

The issue is not related to .NET SDK or .NET SDK logging extensions, you are using `NLog.Targets.Splunk`. This repository is maintained for AWS .NET Logging Extensions. I would suggest you to contact Lambda service team if you need any help in configuring VPC or if any other settings need to be made. 

If you are having issues with configuring Splunk extensions (which I guess is not the case since you are having issue only after deploying to Lambda), kindly contact `NLog.Targets.Splunk` team.

Thanks,
Ashish
