### ISSUE TITLE
No logs appear

### ISSUE THREAD

**Issue by yerttle** [aws/aws-logging-dotnet#158]
Hi there, I am trying to use aws-logging-dotnet within a lambda and am having some problems getting the logs to appears. A LogGroup and LogStream (If that's the right terminology) get created but no logs.

![image](https://user-images.githubusercontent.com/30318189/110478444-47299500-80dc-11eb-8f92-7b21f9c831e7.png)

![image](https://user-images.githubusercontent.com/30318189/110478506-5577b100-80dc-11eb-9027-ecd8b24fadec.png)

I feel like I must doing something dumb but can't see what.

![image](https://user-images.githubusercontent.com/30318189/110478672-7d671480-80dc-11eb-9823-b4e042a7a4d4.png)

![image](https://user-images.githubusercontent.com/30318189/110480224-2a8e5c80-80de-11eb-9c5b-437700976e0b.png)

**Comment by ashishdhingra** [comment]
Hi @yerttle,

Good morning.

Thanks for posting the guidance question. Could you please refer a note at https://github.com/aws/aws-logging-dotnet#aws-lambda which states:
```
These packages batch logging messages in a queue and send messages to CloudWatch Logs using a background thread. The use of the background thread means that the messages are not guaranteed to be delivered when used in AWS Lambda. The reason is because the background thread will be frozen once a Lambda event is processed and may not ever be unfrozen if more Lambda events are not received for some time.

When using Lambda it is recommended to use either the ILambdaContext.Logger.LogLine or the Amazon.Lambda.Logging.AspNetCore package.
```

For your case, instead of `LogManager.GetLogger()`, try using `context.Logger.LogLine()` to log messages to CloudWatch logs. Hope this helps. Kindly confirm if this works and thereafter closet this issue.

Thanks,
Ashish

**Comment by wbgaja** [comment]
Hello,
I am having the same issue - no logs are appearing but the LogGroup and LogStream are creating.    Any resolution?

Thanks,
Gaja
