### ISSUE TITLE
Not up to date with the latest AWSSDK(AWSSDK.SQS 3.7.0.6 with AWS.Logger.AspNetCore 3.1.0.)

### ISSUE THREAD

**Issue by denhaandrei** [aws/aws-logging-dotnet#160]
## Description
My solution is .NET 5. Can`t use AWSSDK.SQS 3.7.0.6 with AWS.Logger.AspNetCore 3.1.0.

## Reproduction Steps
Install nuget packages

### Logs
NU1107 Version conflict detected for AWSSDK.Core. Install/reference AWSSDK.Core 3.7.0.6 directly to project 'MyProject' to resolve this issue. 'MyProject' -> HHS.Synchronization.SQSHandler -> AWSSDK.SQS 3.7.0.6 -> AWSSDK.Core (>= 3.7.0.6 && < 3.8.0) 'MyProject' -> AWS.Logger.AspNetCore 3.1.0 -> AWS.Logger.Core 2.1.0 -> AWSSDK.CloudWatchLogs 3.5.0.24 -> AWSSDK.Core (>= 3.5.1.22 && < 3.6.0).

### Environment
* Build Version: AWS.Logger.AspNetCore 3.1.0
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  .NET 5

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashovlin** [comment]
Sorry about the delay between the SDK and here. Just submitted #161, will let you know when we get it released.

**Comment by ashovlin** [comment]
Just released https://www.nuget.org/packages/AWS.Logger.AspNetCore/3.2.0 which should play nicely alongside AWS SDK 3.7 references.
