### ISSUE TITLE
restrictedToMinimumLevel from appsettings.json is ignored

### ISSUE THREAD

**Issue by arunes** [aws/aws-logging-dotnet#167]
## Description
I know restrictedToMinimumLevel support was added with #165 just recently, but looks like it is not reading from appsettings.json

## Reproduction Steps
Minimum configuration to reproduce.
````
"Serilog": {
  "Using": [
    "AWS.Logger.SeriLog"
  ],

  "LogGroup": "TestLogGroup",
  "Profile": "testLogger",
  "Region": "us-east-2",

  "MinimumLevel": "Debug",
  "WriteTo": [
    {
      "Name": "AWSSeriLog",
      "Args": {
        "restrictedToMinimumLevel": "Error"
      }
    }
  ],
}
````

### Environment

* Build Version: 3.1.0
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  .NET Core 3.1

## Resolution
Adding `restrictedToMinimumLevel` to AWSLoggerSeriLogExtension.cs:92 would fix the issue.
https://github.com/aws/aws-logging-dotnet/blob/b5fab43b4ec0746c6d1b7472b719f4a0f57053df/src/AWS.Logger.SeriLog/AWSLoggerSeriLogExtension.cs#L92

Solution
`return AWSSeriLog(loggerConfiguration, config, iFormatProvider, textFormatter, restrictedToMinimumLevel);`

- [ ] :wave: I can send a pull request for this.
---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @arunes,

Thanks for reporting the issue and suggesting the possible fix. We will examine the issue and if prioritized, include it in future release.

Thanks,
Ashish

**Comment by arunes** [comment]
Hi @ashishdhingra, sounds good!

**Comment by ashishdhingra** [comment]
This has been fixed in [AWS.Logger.SeriLog 3.1.1](https://www.nuget.org/packages/AWS.Logger.SeriLog/3.1.1)
