### ISSUE TITLE
Structured variables now shown when Serilog used

### ISSUE THREAD

**Issue by vladop** [aws/aws-logging-dotnet#169]
I get logs to cloudwatch however variables are not recognized inside aws cloudwatch.
This is my configuration:
```
"serilog": {
    "Using": [
      "AWS.Logger.SeriLog"
    ],
    "LogGroup": "rimacSD-alecs-api-production",
    "IncludeLogLevel": true,
    "IncludeCategory": true,
    "IncludeNewline": true,
    "IncludeException": true,
    "IncludeEventId": true,
    "IncludeScopes": true,
    "Region": "eu-west-1",
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    },
    "Enrich": [ "FromLogContext", "WithMachineName", "WithEnvironmentUserName", "FromLogContext" ],
    "WriteTo": [
      {
        "Name": "AWSSeriLog",
        
      }
    ]
  },
```
If I use alternative Serilog.Sinks.AwsCloudWatch then I get variables inside cloudwatch but I can't figure out how to remove logs
from Microsoft and would rather use this official library.

Inide Program.cs I have this:

```
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseSerilog((hostingContext, services, loggerConfiguration) =>
                {
                    _ = loggerConfiguration.ReadFrom.Configuration(hostingContext.Configuration)
                                        .Enrich.WithProperty("Application", hostingContext.HostingEnvironment.ApplicationName)
                                        .Enrich.WithProperty("Environment", hostingContext.HostingEnvironment.EnvironmentName);
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    _ = webBuilder.UseStartup<Startup>();
                });
    }
```

**Comment by ashishdhingra** [comment]
Hi @vladop,

Good morning.

Thanks for posting the issue. Could you please elaborate what variables you are referring to and provide some code sample to investigate the issue? Any logs would also be helpful. Are you referring to [enrichers](https://github.com/serilog/serilog/wiki/Enrichment) `FromLogContext`, `WithMachineName` and `WithEnvironmentUserName`?

Thanks,
Ashish

**Comment by derekgreer-swagup** [comment]
I'm also seeing an issue with structured logging variables not showing up with the .Net Core API, so I don't think it's Serilog specific.  I have the following configuration:

```
builder.Services.AddLogging(config =>
{
    config.AddAWSProvider(builder.Configuration.GetAWSLoggingConfigSection());
    config.SetMinimumLevel(LogLevel.Trace);
});
```

Here is my appSettings.json:

```
  "AWS.Logging": {
    "Region": "us-east-2",
    "LogGroup": "WidgetService",
    "LogLevel": {
      "Default": "Information",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
```

I'm logging the following structured log:

```
_logger.LogError("error test message {Test} {Field1} {Field2}", "Text", "1", 42);
```

I would expect this to be sent as a structured log to CloudWatch, but it appears to send an interpolated string:

![image](https://user-images.githubusercontent.com/96131108/150843685-47303e06-feb6-48c7-a23b-3b24b5a2b76e.png)

Here, I would expect to see the variables:
@Test    Text
@Field1   1
@Field2   42

It appears the library doesn't preserve the message.  I'm guessing this is what the OP was expressing, that when they use Serilog with Serilog's AWS sink that it correctly preserves the variables, but when using the "official" microsoft library for logging to CloudWatch with Serilog that it isn't preserving the variables.  Seems like it's because the core library just doesn't properly support structured logging.

**Comment by derekgreer-swagup** [comment]
This is a follow-up to my previous comment.

My cloud experience to date has primarily been in Azure.  Upon seeing AWS CloudWatch's interface, I presumed it was facilitating discrete custom fields the way Azure AppInsights does.  Using Microsoft's AppInsights logging provider, it takes the structured logging data and maps it to the custom properties for the log entry.  After learning a bit more about CloudWatch, I'm now thinking that it doesn't quite work that way.  It seems it has the notion of standard fields and "discovered" fields, but it it doesn't seem to deal with custom fields in quite the same way as AppInsights.  If this is indeed the way it works, it would seem that the CloudWatch provider really has no other recourse but to use.Net Core's structured logging data for string interpolation, in which case it isn't a bug in this library so much as just a limitation of CloudWatch.

**Comment by ashishdhingra** [comment]
Needs review with team to investigate structured logging and how it could be supported by AWS logging libraries.

**Comment by wahmedswl** [comment]
This is really a problem because if we need to push message to Standard Log-group then we are doomed. We are using Serilog console sink and it works pretty well but it logs to the lambda group. 
We need to push messages to standard log-group so we implemented using ```AWS.Logger.SeriLog``` but its pushing messages as raw. This is the event different between Serilog console sink vs ```AWS.Logger.SeriLog```.

![image](https://user-images.githubusercontent.com/15020561/211234963-9b328f7d-d0b0-4f38-ad08-7f7a1557358b.png)

If json is written to message just like serilog console sink is doing, everything will work but ```AWS.Logger.SeriLog``` is doing text transform on the log message but all context fields are lost. Only thing pushed to logs is formatted message, ```Information("Serilog with Lambda logs to CloudWatch with Level = Information worked on Iteration {Iteration}", i + 1);```

**Comment by wahmedswl** [comment]
There might be something OFF the way normal implementation works but this article gives the right way to implement structured logging for Cloudwatch. 

https://www.rahulpnath.com/blog/amazon-cloudwatch-logs-dotnet/

**Comment by louisobasohan** [comment]
> There might be something OFF the way normal implementation works but this article gives the right way to implement structured logging for Cloudwatch.
> 
> https://www.rahulpnath.com/blog/amazon-cloudwatch-logs-dotnet/

The step in the link above does not still produce structured logs. Does anyone have an idea on how to address this issue? When I run the application locally and log in to cloud watch, the structured logs are shown correctly, but when the lambda is deployed and runs, the logs show in plaintext, and all the enrich information are lost.

**Comment by wahmedswl** [comment]
@louisobasohan You can switch to ```Serilog.Sinks.AwsCloudWatch``` for proper structured logging.

**Comment by louisobasohan** [comment]
> @louisobasohan You can switch to `Serilog.Sinks.AwsCloudWatch` for proper structured logging.

Serilog.Sinks.AwsCloudWatch is also giving me the same output. Also, I'm using .NET6

**Comment by wahmedswl** [comment]
```
Log.Logger = new LoggerConfiguration()
                .Destructure.JsonNetTypes()
                .ReadFrom.Configuration(configurationRoot)
                .WriteTo.Console(new CompactJsonFormatter())
                .WriteTo.Logger(x => x.Filter.ByIncludingOnly(y => y.Level <= LogEventLevel.Information).WriteTo.AmazonCloudWatch(new CloudWatchSinkOptions { LogGroupName = "ServerlessApp/Info", TextFormatter = new CompactJsonFormatter(), Period = TimeSpan.FromMilliseconds(100) }, new AmazonCloudWatchLogsClient(regionEndpoint)))
                .WriteTo.Logger(x => x.Filter.ByIncludingOnly(y => y.Level > LogEventLevel.Information).WriteTo.AmazonCloudWatch(new CloudWatchSinkOptions { LogGroupName = "ServerlessApp/Error", TextFormatter = new CompactJsonFormatter(), Period = TimeSpan.FromMilliseconds(100) }, new AmazonCloudWatchLogsClient(regionEndpoint)))
                .CreateLogger();
```

I guess you are missing the Formatter.

**Comment by louisobasohan** [comment]
> ```
> Log.Logger = new LoggerConfiguration()
>                 .Destructure.JsonNetTypes()
>                 .ReadFrom.Configuration(configurationRoot)
>                 .WriteTo.Console(new CompactJsonFormatter())
>                 .WriteTo.Logger(x => x.Filter.ByIncludingOnly(y => y.Level <= LogEventLevel.Information).WriteTo.AmazonCloudWatch(new CloudWatchSinkOptions { LogGroupName = "ServerlessApp/Info", TextFormatter = new CompactJsonFormatter(), Period = TimeSpan.FromMilliseconds(100) }, new AmazonCloudWatchLogsClient(regionEndpoint)))
>                 .WriteTo.Logger(x => x.Filter.ByIncludingOnly(y => y.Level > LogEventLevel.Information).WriteTo.AmazonCloudWatch(new CloudWatchSinkOptions { LogGroupName = "ServerlessApp/Error", TextFormatter = new CompactJsonFormatter(), Period = TimeSpan.FromMilliseconds(100) }, new AmazonCloudWatchLogsClient(regionEndpoint)))
>                 .CreateLogger();
> ```
> 
> I guess you are missing the Formatter.

Thanks Wahmedswl, writing to console with the JsonFormatter solved the issue.

**Comment by wahmedswl** [comment]
@louisobasohan Yes, if you writing to the log group of Lambda, you just need ```Serilog.Sinks.Console```. If you need to write to other/centralized log group, then you need to use ```Serilog.Sinks.AwsCloudWatch```.
