### ISSUE TITLE
Adding credentials to config

### ISSUE THREAD

**Issue by volkanx** [aws/aws-logging-dotnet#17]
Hello,
I've tried creating a default profile but doesn't seem to work. When I try to log something I get this exception:

> An unhandled exception occurred and the process was terminated.
> 
> Application ID: /LM/W3SVC/2/ROOT
> 
> Process ID: 36640
> 
> Exception: System.NullReferenceException
> 
> Message: Object reference not set to an instance of an object.
> 
> StackTrace:    at AWS.Logger.Core.AWSLoggerCore.Finalize() in D:\Jenkins\jobs\aws-logging-dotnet\workspace\src\AWS.Logger.Core\Core\AWSLoggerCore.cs:line 146
> 

In the documentation it says "o use a specific AWS credential profile add a Profile under the appender node." 

Does anyone have an example of specifying the profile this way?

Also is it possible to add the credentials directly to config without creating a profile? I think the application would be self-contained that way and would work if installed on a new machine. Otherwise some extra configuration on each machine would be required. Maybe I'm missing a point but I think direct credentials in the config would be easier to manage.

Anyway, thanks in advance.

**Comment by ruskindantra** [comment]
Yes, I would be quite interested to learn how to set the credentials as well, we don't use environment variables, does this have other ways in which credentials can be provided?

**Comment by harshane** [comment]
Same case with me, I need example of how to set the credentials. @volkanx or @ruskindantra Let me know if you found solution for it.

**Comment by peterdeme** [comment]
@harshane @ruskindantra 
There's a thing called credential chain. If the credential not found in one item, it'll try the next one.
http://docs.aws.amazon.com/sdk-for-net/v2/developer-guide/net-dg-config-creds.html#creds-assign

Also see this file:
https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L46-#L56
