### ISSUE TITLE
CloudWatch Network Error - Unable to get IAM security credentials from EC2 Instance Metadata Service.

### ISSUE THREAD

**Issue by scraperg** [aws/aws-logging-dotnet#170]
## Description
Hi,

We are attempting to use AWS.Logger.NLog to log to CloudWatch from a .Net Framework site running on EC2 via Elastic Beanstalk. Making it more frustrating, the logging has worked _occasionally_, but not consistently. We have not been able to isolate the difference between when it works and when it does not.

Any help is appreciated.

## Reproduction Steps

Our NLog.config is as follows:
```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog autoReload="true"
      xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwExceptions="true"
      internalLogLevel="Debug"
      internalLogFile="c:\scratch\nlog-internal.log">
  <targets>
    <target name="aws" type="AWSTarget" logGroup="my-log-group" region="us-west-2" />
    <target name="file" type="File" fileName="/scratch/logs/app.log"/>
  </targets>
  <rules>
    <logger name="*" minlevel="Info" writeTo="file,aws"/>
  </rules>
  <extensions>
    <add assembly="NLog.AWS.Logger"/>
  </extensions>
</nlog>
```

The application runs as expected on Beanstalk, and the _local_ file logging works. But no logs are written to "my-log-group" in CloudWatch. NLog's internal log contains lots of CloudWatch Network Errors.

### Logs

Details from NLog's internal logging:

> 2021-07-15 14:38:25.8514 Error AWSTarget(Name=aws) - CloudWatch Network Error - ServiceUrl=https://logs.us-west-2.amazonaws.com/ Exception: Amazon.Runtime.AmazonServiceException: Unable to get IAM security credentials from EC2 Instance Metadata Service.
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()
   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()

Based on the information here https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/instancedata-data-retrieval.html , we tested retrieving a token _on_ the EC2 instance from the Session Manager command line. It seems to work.

> PS C:\scratch> $token = Invoke-RestMethod -Headers @{"X-aws-ec2-metadata-token-ttl-seconds" = "21600"} -Method PUT –Uri http://169.254.169.254/latest/api/token
PS C:\scratch> echo $token
AQAEAOSoRjXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==
PS C:\scratch> Invoke-RestMethod -Headers @{"X-aws-ec2-metadata-token" = $token} -Method GET -Uri http://169.254.169.254/latest/meta-data/
ami-id
ami-launch-index
ami-manifest-path
block-device-mapping/
events/
hibernation/
hostname
iam/
identity-credentials/
instance-action
instance-id
instance-life-cycle
instance-type
local-hostname
local-ipv4
mac
metrics/
network/
placement/
profile
reservation-id
security-groups
services/
PS C:\scratch>

### Environment

* Build Version: 
  - AWS.Logger.Core v3.0.0
  - AWS.Logger.NLog v3.0.0
  - AWSSDK.CloudWatchLogs v3.7.1.3
  - AWSSDK.Core v3.7.0.31
* OS Info: IIS 10.0 running on 64bit Windows Server 2016/2.6.6
* Build Environment: MSBuild v16.10.0.26302
* Targeted .NET Platform:  .NET Framework 4.7.2

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @scraperg,

Good morning.

From the log that you shared, it clearly indicates that the credentials were unable to be received from the EC2 Instance Metadata service based on the [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/creds-assign.html). Would it be possible for you to provide trimmed down version of sample code solution to troubleshoot the issue? Also check the load and performance counters on your EC2 instance as it can also affect credential retrieval. The timeout for getting credentials from EC2 instance metadata service is 5000 milliseconds. The issue could also happen if IMDS is disabled on EC2 instance, in which case [EC2InstanceMetadata](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Util/EC2InstanceMetadata.cs) would not return any credentials and subsequently exception is thrown by credential resolution process.

Thanks,
Ashish

**Comment by scraperg** [comment]
Hi @ashishdhingra ,

Thanks for taking a look. For .Net Framework I think [this page](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html#creds-assign) describes how credentials are resolved -- with EC2 instance metadata being considered last. Is my understanding correct?

The load on the EC2 instance is low -- it isn't being used other than trying to get the logs working. 

How can I determine if IMDS is disabled on the EC2 instance? I don't see it mentioned on the EC2 Console. I thought the successful query to `http://169.254.169.254/latest/api/token` (in the original comment) showed it was working.

I will attempt to create a small repro case.

Thanks again.

**Comment by scraperg** [comment]
Our issue was due to a proxy was interfering with the requests to the Instance Metadata service. 

This issue was helpful, even though it refers to .Net Core, not .Net Framework: https://github.com/aws/aws-sdk-net/issues/1518

Thanks for the help.
