### ISSUE TITLE
AspNetCore logger - CloudWatch is only missing direct console output

### ISSUE THREAD

**Issue by spiffyhat** [aws/aws-logging-dotnet#178]
## Description
I don't know if I'm just misunderstanding the situation, but the logger seems to be sending everything except direct console output (Console.Write, Console.WriteLine etc.) to Cloudwatch. It is, for example, successfully logging from Microsoft.AspNetCore, and logging from within my own proprietary library to CloudWatch, but any console output is not sent to Cloudwatch, even though it does appear in the docker logs when I SSH into the EC2 instance.

Relevant sections of my code:

Program.cs
![image](https://user-images.githubusercontent.com/70716178/140681484-ccc33707-00c6-482f-bb17-1683bb0e190d.png)

appsettings.json
![image](https://user-images.githubusercontent.com/70716178/140681610-e4f00bc6-fa29-4ef7-ae69-88f25a5f00ea.png)

Code within the ConfigureServices method in Startup.cs
![image](https://user-images.githubusercontent.com/70716178/140681753-5b609273-ded5-4c12-b95b-0883b70c17e8.png)

Some example logs that are successfully writing to CloudWatch:
![image](https://user-images.githubusercontent.com/70716178/140681902-0458992a-98fc-473b-a2cc-4b4e50797c3c.png)

Console output that was missed but appears in the docker container's logs ("Health Check controller reached."):
![image](https://user-images.githubusercontent.com/70716178/140682046-8c5585e1-30f2-4272-92ff-828cf03551c5.png)
![image](https://user-images.githubusercontent.com/70716178/140682182-2d5bbd31-6552-4b4b-9875-5089581da1e5.png)

Should this console output be getting picked up and logged to CloudWatch? My understanding is that because Console.WriteLine is on the STDOUT stream, it should be visible on CloudWatch as well. 

### Environment

* Build Version:  AWS.Logger.AspNetCore 3.2.0
* OS Info:  .NET Core console application running in a Linux docker container
* Build Environment:  AWS ECS 
* Targeted .NET Platform:  .NET Core 3.1

This is possibly a :bug: bug-report, either that or I am misunderstanding how this package should be performing. Let me know if you need any more information.

**Comment by ashishdhingra** [comment]
Hi @spiffyhat,

Good morning.

Thanks for posting the question. As [Readme](https://github.com/aws/aws-logging-dotnet#aspnet-core-logging) mentions, ASP.NET Core introduced a new [logging framework](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0) that has providers configured to send logs to destinations (Console, Debug, EventSource, Event Log). It also allows to [Create a custom logger](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#create-a-custom-logger). The `AWS.Logger.AspNetCore` NuGet package provides a log provider which adds CloudWatch Logs as a destination for the logs. The logging statements could be sent to CloudWatch logs using methods provided by `ILogger` interface. It is not meant to capture any information logged via `Console.Write()` or `Console.WriteLine()`. 

Kindly note that this is different from Lambda logging implementation where it captures the output sent to Console.

Hope this provides some guidance.

Thanks,
Ashish

**Comment by spiffyhat** [comment]
Hi Ashish, thank you for clarifying the functionality. I was mistakenly thinking the functionality would be the same as with Lambda where the console output is captured. This issue can definitely be closed.
