### ISSUE TITLE
Configurable Flush Timeout

### ISSUE THREAD

**Issue by wozzo** [aws/aws-logging-dotnet#180]
## Describe the Feature
In applications that produce large amounts of logging and then close, e.g. CLI applications, the currently hard coded 30 second flush timeout may not be sufficient and will result in a loss of logs.
Allow configuration of the 30 second timeout so that enough time to send all logs can be given.

### Is your Feature Request related to a problem?
Yes, we have a CLI application that produces large amounts of logs and then closes, and we're missing vital logging.

## Proposed Solution
Add a new `TimeSpan` property to the `IAWSLoggerConfig` config and use this in place of the hard coded 30 seconds in the `AWSLoggerCore`.

### Describe alternatives you've considered
Changing `BatchPushInterval` and `BatchSizeInBytes`. Still missing logs 

### Environment
Run on Windows, but likely a cross platform issue.

[x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
This is released in the following packages:
- [AWS.Logger.AspNetCore 3.3.0](https://www.nuget.org/packages/AWS.Logger.AspNetCore/3.3.0)
- [AWS.Logger.Core 3.1.0](https://www.nuget.org/packages/AWS.Logger.Core/3.1.0)
- [AWS.Logger.Log4net 3.3.0](https://www.nuget.org/packages/AWS.Logger.Log4net/3.3.0)
- [AWS.Logger.NLog 3.1.0](https://www.nuget.org/packages/AWS.Logger.NLog/3.1.0)
- [AWS.Logger.SeriLog 3.2.0](https://www.nuget.org/packages/AWS.Logger.SeriLog/3.2.0)
