### ISSUE TITLE
AWS NLog -  UseNLog is not working

### ISSUE THREAD

**Issue by SDGN1983** [aws/aws-logging-dotnet#182]
## Description

I am trying to use NLog with .Net core aws serverless application to write logs to AWS CloudWatch. A few logs are getting logged and some of them are ignored. The logging works fine when the application is run locally from "LocalEntryPoint" and all the logs are written to the log group specified. 
Here is my config file.
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"	
      internalLogToConsole="true"
	  internalLogToConsoleError="true">

  <extensions>
	<add assembly="NLog.AWS.Logger" />	  
  </extensions>

  <targets>
	<target name="aws" type="AWSTarget" logGroup="Apps_MatterSphere_Integration_Internal_DEV" region="ap-southeast-2" 
			layout=	"${uppercase:${level}}|${machinename}|${callsite}|${message} ${exception}">		
	</target>   
  </targets>

  <rules>
	<logger name="Microsoft.*" minlevel="Trace" writeTo="blackhole" final="true" />
    <logger name="*" minlevel="Trace" writeTo="aws" />
  </rules>
</nlog>

**LambdaEntryPoint**
 ```
protected override void Init(IWebHostBuilder builder)
        {
            var logger = NLogBuilder.ConfigureNLog("NLog.config").GetCurrentClassLogger();         
            try
            {                           
                logger.Info("Inside startup");
                builder.UseStartup<Startup>()
                  .UseNLog();                

            }
            catch (Exception ex)
            {
                  logger.Error(ex, $"stopped becuase of exception.");               
            }
            finally
            {
                NLog.LogManager.Flush();
            }

        }
```

The log info  "Inside startup" is always written to the logs. 

But the logs from the controller are not getting logged into the cloud watch log group. 

    public class ValuesController : ControllerBase
    {
        private readonly ILogger<ValuesController> _logger;
        public ValuesController(ILogger<ValuesController> logger)
        {
            _logger = logger;
        }

        // GET api/values
        [HttpGet]
        public IEnumerable<string> Get()
        {
            _logger.LogInformation("Retrieving values");
            return new string[] { "value1", "value2", "value3" };
        }
}

**Comment by snakefoot** [comment]
What if you try this:

```c#
        protected override void Init(IWebHostBuilder builder)
        {
            NLog.LogManager.Setup().SetupExtensions(e => e.AutoLoadAssemblies(false))
                 .RegisterNLogWeb()
                 .LoadConfigurationFromFile("nlog.config")
                 .LoadConfiguration(builder => builder.LogFactory.AutoShutdown = false);

            builder.UseStartup<Startup>().UseNLog(new NLogAspNetCoreOptions() { ShutdownOnDispose = true, RemoveLoggerFactoryFilter = true });
        }
```

**Comment by SDGN1983** [comment]
> What if you try this:
> 
> ```cs
>         protected override void Init(IWebHostBuilder builder)
>         {
>             NLog.LogManager.Setup().SetupExtensions(e => e.AutoLoadAssemblies(false))
>                  .RegisterNLogWeb()
>                  .LoadConfigurationFromFile("nlog.config", optional: false)
>                  .LoadConfiguration(builder => builder.LogFactory.AutoShutdown = false);
> 
>             builder.UseStartup<Startup>().UseNLog(new NLogAspNetCoreOptions() { ShutdownOnDispose = true, RemoveLoggerFactoryFilter = true });
>         }
> ```

Thank you.
This code is also producing similar results as the above code. Not all the logs are written to the log group. 
There is a default log group created for the lambda function and I can see all the logs written there. Is it a drawback of using nlog for lambda function?

In the readme for this project, its written like this

> AWS Lambda
> These packages batch logging messages in a queue and send messages to CloudWatch Logs using a background thread. The use of the background thread means that the messages are not guaranteed to be delivered when used in AWS Lambda. The reason is that the background thread will be frozen once a Lambda event is processed and may not ever be unfrozen if more Lambda events are not received for some time.
> 
> When using Lambda it is recommended to use either the ILambdaContext.Logger.LogLine or the Amazon.Lambda.Logging.AspNetCore package.

Does it mean we cant use NLog with lambda ? 

Thanks  a lot

**Comment by ashishdhingra** [comment]
> > What if you try this:
> > ```cs
> >         protected override void Init(IWebHostBuilder builder)
> >         {
> >             NLog.LogManager.Setup().SetupExtensions(e => e.AutoLoadAssemblies(false))
> >                  .RegisterNLogWeb()
> >                  .LoadConfigurationFromFile("nlog.config", optional: false)
> >                  .LoadConfiguration(builder => builder.LogFactory.AutoShutdown = false);
> > 
> >             builder.UseStartup<Startup>().UseNLog(new NLogAspNetCoreOptions() { ShutdownOnDispose = true, RemoveLoggerFactoryFilter = true });
> >         }
> > ```
> 
> Thank you. This code is also producing similar results as the above code. Not all the logs are written to the log group. There is a default log group created for the lambda function and I can see all the logs written there. Is it a drawback of using nlog for lambda function?
> 
> In the readme for this project, its written like this
> 
> > AWS Lambda
> > These packages batch logging messages in a queue and send messages to CloudWatch Logs using a background thread. The use of the background thread means that the messages are not guaranteed to be delivered when used in AWS Lambda. The reason is that the background thread will be frozen once a Lambda event is processed and may not ever be unfrozen if more Lambda events are not received for some time.
> > When using Lambda it is recommended to use either the ILambdaContext.Logger.LogLine or the Amazon.Lambda.Logging.AspNetCore package.
> 
> Does it mean we cant use NLog with lambda ?
> 
> Thanks a lot

@SDGN1983 You are correct. When working with Lambda, it is recommended to use either the `ILambdaContext.Logger.LogLine` or the `Amazon.Lambda.Logging.AspNetCore` package (for serverless applications).
