### ISSUE TITLE
Add support for Embedded Metric Format by including the expected header

### ISSUE THREAD

**Issue by frozenberg** [aws/aws-logging-dotnet#186]
The embedded metric format has a specific schema that is expected for CloudWatch to correctly scrape logs and emit metrics: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html

I've got the logs being emitted in the right format using a mix of the `AWS.Logger.SeriLog` package and the [aws-embedded-metrics-dotnet](https://github.com/awslabs/aws-embedded-metrics-dotnet) package, except for one detail: the schema requires a header to be included in the call to the `PutLogEvents` API (`x-amzn-logs-format: json/emf`). Would it be possible for you to expose an option that lets users include a header or simply a toggle to enable embedded metrics?

**Comment by ashishdhingra** [comment]
Needs review with the team whether simply exposing way to pass headers would enable EMF.

**Comment by gordonpn** [comment]
@frozenberg @ashishdhingra 

Any EMF logs that can reach CloudWatch Logs will now be parsed and metrics can be generated from them. You don't need the EMF header anymore.

If you face any issues, you can get in touch with me!

**Comment by ashishdhingra** [comment]
@gordonpn Thanks for your input.
@frozenberg Could you please check the same at your end and confirm if we could close this issue?
