### ISSUE TITLE
Nlog to aws cloudwatch not working when passing lookup values

### ISSUE THREAD

**Issue by hareeshmakani** [aws/aws-logging-dotnet#192]
```xml
<?xml version="1.0" encoding="utf-8"?>

<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="info"
      internalLogFile="c:\LogsDemo\NLogs\internal-nlog.txt">
	
	<extensions>
		<add assembly="NLog.AWS.Logger" />
	</extensions>
	
	<targets>
		<target name="aws" type="AWSTarget" logGroup="NLog.ConfigExample2" profile="'${var:profile}'" region="'${var:region}'"/>		
	</targets>
	
	<rules>
		<logger name="*" minlevel="Info" writeTo="aws" />
	</rules>
</nlog>
```

The above code to log data into aws cloudwatch is not working when I try to pass region & profile values from startup class.

        LogManager.Configuration.Variables["region"] = "ap-south-1";
        LogManager.Configuration.Variables["profile"] = "default";
However when I hardcoded the values it's working.

```xml
<target name="aws" type="AWSTarget" logGroup="NLog.ConfigExample" profile="default" region="ap-south-1"/>
```

**Comment by snakefoot** [comment]
See also advice given here: https://github.com/NLog/NLog/issues/4841

**Comment by ashishdhingra** [comment]
Hi @hareeshmakani,

Good morning.

Thanks for posting the question.

Few things to note about dynamic variables:
- Per [NLog: Configuration file: Variables](https://github.com/NLog/NLog/wiki/Configuration-file#variables), Dynamic mode only works for properties of the type NLog Layout.
- Per [NLog: Update config in code](https://github.com/NLog/NLog/wiki/Configure-from-code#update-config-in-code), it actually reapplies the updated configuration to `LogManager.Configuration`. This support the input shared by @snakefoot in https://github.com/aws/aws-logging-dotnet/issues/51#issuecomment-440839779.

Does the guidance shared by @snakefoot doesn't work for you. Based on 2nd point above, this issue doesn't appear to be an issue with the [AWS.Logger.Nlog](https://www.nuget.org/packages/AWS.Logger.NLog/) package (it is really a wrapper around NLog library), but rather investigation/guidance on how NLog configuration works.

Thanks,
Ashish
