### ISSUE TITLE
How can I apply colon-delimited filter in Clouwatchlogs filter pattern

### ISSUE THREAD

**Issue by rajasekaran07** [aws/aws-logging-dotnet#2]
Hi team,

I am not sure this is the correct place to ask my request. I am trying to put some pattern while passing my Cloudwatch logs to AWS ES. Let's assume my logs look like below lines.

```
Running:on:http://localhost:8081
Running:on:http://localhost:8081
Running:on:http://localhost:8081
Running:on:http://localhost:8081
Running:on:http://localhost:8081
Running:on:http://localhost:8081
```

How can I split using colon-delimited filter in AWS Cloudwatch Filter pattern. Kindly someone suggest how to fix this.

Regards,
Raja

**Comment by PavelSafronov** [comment]
For questions about the AWS Cloudwatch Filter and Pattern syntax you'll want to refer to the [official documentation page](http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html) for that feature, the general [Amazon CloudWatch Logs User Guide](http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/WhatIsCloudWatchLogs.html), and the [Amazon Cloudwatch forum](https://forums.aws.amazon.com/forum.jspa?forumID=138).
