### ISSUE TITLE
System.OperationCanceledException: The request was aborted

### ISSUE THREAD

**Issue by pyisoeyz** [aws/aws-logging-dotnet#20]
I've provided role to EC2 but i'm facing aws-logger-error.txt

> 
>   :System.OperationCanceledException: The request was aborted: The request was canceled. ---> System.Net.WebException: The request was aborted: The request was canceled.
>    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__16.MoveNext()
>    --- End of inner exception stack trace ---
>    at Amazon.Runtime.Internal.HttpRequest.<GetResponseAsync>d__16.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---

**Comment by spati2** [comment]
It seems that the Monitor logging task is being cancelled and is not an error with the logging library. I will make the change to omit this log message. Are your log messages showing up cloudwatch logs?

**Comment by pyisoeyz** [comment]
yes it does. but it is not logging if i just provide EC2 Role, I must setup the profile. Is it expected behaviour?
