### ISSUE TITLE
Using AWS.Logger.SeriLog in Lambda Web API throws "Endpoint request timed out"

### ISSUE THREAD

**Issue by boyce-developer** [aws/aws-logging-dotnet#204]
### Describe the bug

I have been using AWS.Logger.SeriLog 3.1.1 to create logs into Cloudwatch from my Web API built on .net 6.0. It has been working fine. Recently we are attempting to migrate our Web API to Lambda. We got everything working except for Serilog logging into Cloudwatch using this plugin. It logs fine into the Lambda's default Cloudwatch logs. But not the custom Cloudwatch stream.

To make sure that it was a problem with this package, I created a default Serverless Web Api using the template from AWS Toolkit for Visual Studio. Created a sample application. Added Serilog plugin and configuration. If I don't enable WriteTo.AWSSeriLog, Serilog works fine. But as soon as I enable that, it was throwing the timed out error.

I tried to debug in my local by running the API in my local. Interestingly, it doesn't hit any errors and the log is created in Cloudwatch. So can confirm that the implementation and credentials are working without issues. For some reason, it can't seem to reach there from Lambda.

### Expected Behavior

Logs are created in custom Cloudwatch stream as configured.

### Current Behavior

Getting {"message": "Endpoint request timed out"} from Lambda when called.

### Reproduction Steps

Create a project using the template from AWS Toolkit.
![image](https://user-images.githubusercontent.com/85203376/171947666-fa9b156e-768c-4508-bf5d-31502f60b259.png)

![image](https://user-images.githubusercontent.com/85203376/171947791-813945d3-53d6-44a8-8007-7b7e3c910852.png)

Once created, enable Serilog in code in LambdaEntryPoint class. I called it in the overriding Init method. Interestingly, the LambdaEntryPoint initialization of Serilog Logger doesn't persist to the Web API. So I moved the Logger creation to a common static class called SharedEntryPoint and called it from both LambdaEntryPoint and Startup.

```
public static Serilog.Core.Logger SetupLogger()
{
    var awsConfig = new AWSLoggerConfig("Aws.Serverless.Api.Logs")
    {
        Credentials = new BasicAWSCredentials("<ACCESSKEY>",
            "<SECRETKEY>"),
        Region = "ap-southeast-2",
    };

    // Add Logger services
    try
    {
        var loggerConfig = new LoggerConfiguration()
            .Enrich.FromLogContext()
            .WriteTo.AWSSeriLog(awsConfig)
            .WriteTo.Console(new JsonFormatter(null, true, CultureInfo.InvariantCulture));

        return loggerConfig.CreateLogger();
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
        throw;
    }
}
```

And in LambdaEntryPoint class,
```
protected override void Init(IWebHostBuilder builder)
{
    Log.Logger = SharedEntryPoint.SetupLogger();

    try
    {
        Log.Information("Starting up using Lambda Entry Point...");

        builder
            .UseConfiguration(SharedEntryPoint.Configuration)
            .UseStartup<Startup>();

        Log.Information("Shutting down using Lambda Entry Point...");
    }
    catch (Exception ex)
    {
        Log.Fatal(ex, "Api host terminated unexpectedly");
    }
    finally
    {
        Log.CloseAndFlush();
    }
}

protected override void Init(IHostBuilder builder)
{
    builder
        .UseSerilog();
}
```

In Startup class,
```
public void ConfigureServices(IServiceCollection services)
{
    // add application service instances
    services.AddSingleton<IConfiguration>(Configuration);

    var logger = SharedEntryPoint.SetupLogger();
    services.AddSingleton<Serilog.ILogger>(logger);

    services.AddControllers();
}
```

This code works when I don't call `.WriteTo.AWSSeriLog(awsConfig)`. But when I have that enabled, it throws the timeout error.

### AWS .NET SDK and/or Package version used

Nuget Packages included.
- "Amazon.Lambda.AspNetCoreServer" Version="7.2.0"
- "AWS.Logger.SeriLog" Version="3.1.1"
- "Microsoft.Extensions.Configuration.Json" Version="6.0.0"
- "Serilog" Version="2.11.0"
- "Serilog.AspNetCore" Version="5.0.0"
- "Serilog.Extensions.Logging" Version="3.1.0"
- "Serilog.Settings.Configuration" Version="3.3.0"
- "Serilog.Sinks.Console" Version="4.0.1"

### Targeted .NET Platform

.NET 6

### Operating System and version

AWS Lambda

**Comment by ashishdhingra** [comment]
Hi @boyce-developer,

Good afternoon.

Could you please check/advise on the following:
- Are you using hard coded basic credentials for your application in actual Lambda environment?
- Could you please check if the IAM user/role associated with Lambda (or with the Serilog configuration) has the following permissions (as mentioned at https://github.com/aws/aws-logging-dotnet#required-iam-permissions):
```C#
logs:CreateLogGroup
logs:CreateLogStream
logs:PutLogEvents
logs:DescribeLogGroups
```
The logging libraries internally also need to describe log groups to determine the destination log stream, hence additional permissions are needed in addition to `logs:PutLogEvents`.

Thanks,
Ashish

**Comment by boyce-developer** [comment]
Hi @ashishdhingra 

> Are you using hard coded basic credentials for your application in actual Lambda environment?

I used it from configuration in my main application. But on the test application, I hardcoded the basic credentials. I verified by logging the credentials in the logs to confirm that it was correct.

> Could you please check if the IAM user/role associated with Lambda (or with the Serilog configuration) has the following permissions (as mentioned at https://github.com/aws/aws-logging-dotnet#required-iam-permissions)

I have given complete access to Cloudwatch Logging for that user account.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "logs:*"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```
I can confirm the permissions are correct because when I run the API in local, it is creating logs in the right streams.

**Comment by ashishdhingra** [comment]
@boyce-developer Could you please check the note at https://github.com/aws/aws-logging-dotnet#aws-lambda. It specifies that it is recommended to use either the ILambdaContext.Logger.LogLine or the [Amazon.Lambda.Logging.AspNetCore](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Logging.AspNetCore) package for Lambda environment. May be that is the reason it's timing out when executing in actual Lambda environment. 

So you might want to consider using [ASP.NET Core Logging](https://github.com/aws/aws-logging-dotnet#aspnet-core-logging) package.

Thanks,
Ashish

**Comment by boyce-developer** [comment]
Hi @ashishdhingra ,

I have used that one and confirmed it to be working. However, it doesn't capture the information as neatly and condensed as I wanted to. Serilog was able to do that as I can enrich the log with header and other information.

FYI, if it's a Lambda application directly, Serilog seems to be working fine. I have a Lambda function that gets triggered via Cloudwatch and executes an operation. At the function construction call, I am initializing Serilog. And that seems to work perfectly fine and the logs are being created in Cloudwatch as I wanted it.

So it has something to do with the execution of Serilog from Web API that runs in Lambda. A direct Web API works. A direct Lambda works. Only a Web API running in Lambda doesn't work.

Kind Regards,
Boyce

**Comment by ashishdhingra** [comment]
@boyce-developer Could you please advisse:
- What `Log.CloseAndFlush();` call in `LambdaEntryPoint.Init()` does?
- Have you by any chance set `Serilog:ServiceUrl` in your configuration?

Thanks,
Ashish

**Comment by boyce-developer** [comment]
Apologies for the delay. Work was busy.

`LambdaEntryPoint.Init()` is automatically called by the Lambda function as the exection.

The reason why I call `Log.CloseAndFlush();` is because sometimes the log buffer contains the last log that doesn't get posted before the application terminates in case of error. Calling this on the end of the execution ensures that even on the point of error, the last log gets published. It works fine in direct Lambda application.

I did not set `Serilog:ServiceUrl`. Not sure what I'm supposed to set for this anyway.

**Comment by boyce-developer** [comment]
@ashishdhingra Are you able to open this?

**Comment by boyce-developer** [comment]
> @boyce-developer I think your problem is the `Log.CloseAndFlush()` call in the init. The init method is just configuring the services for the ASP.NET Core application is does not run it. I assume you are falling the examples online that wrap the the ASP.NET Core startup in `Program.cs` with this try catch. In those examples there is the blocking `CreateHostBuilder(args).Build().Run()` call that blocks for the lifespan of the ASP.NET Core application and the flush is only called when the program exists. In your case you are configuring Serilog, adding some services to the `IWebHostBuilder` and then closing Serilog as control is passed up to the base class to startup ASP.NET Core.
> 
> I do still worry after you fix that issue you could miss some logging messages due to this libraries use of a background thread that might get frozen in Lambda and never be unfrozen to finish its queue sending messages to CloudWatch Logs.

Hi normj.

Thank you for the explanation. Is there a workaround for the problem to get `.WriteTo.AWSSeriLog(awsConfig)` working?

The reason I wrap the `builder` in the LambdaEntryPoint is because I wanted to capture any exceptions that occurred during the lambda starting on the same log file. Didn't want to maintain two separate log files for same application.

Is that my only option then? Get the Serilog initialized in Startup and then use a different means to log the Lambda init errors?

**Comment by normj** [comment]
@boyce-developer I can't think of any work around. I created this feature request to add a flushing capabilities into our libraries. Please take a look and let me know if that would help you. If so please +1 to help prioritize the feature. I'm going to close this issue as I don't think there is anymore we can do till we fine tuned and implement the feature request. 

https://github.com/aws/aws-logging-dotnet/issues/211
