### ISSUE TITLE
LogStreamNamePrefix does not log and idles with AWS.Logger.Log4net

### ISSUE THREAD

**Issue by Rodriguevb** [aws/aws-logging-dotnet#209]
### Describe the bug

Hello,

With a very small code example, I can log something without setting the LogStreamNamePrefix property. But if I set it, the log is ignored and the software idles for a while before closing (timeout).

### Expected Behavior

I expected to log something with a defined prefix.

### Current Behavior

Timeout and no log in AWS CloudWatch

### Reproduction Steps

The project with net6 (but also with all versions)
```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="AWS.Logger.Log4net" Version="3.3.0" />
	</ItemGroup>
</Project>
```

```
using AWS.Logger.Log4net;
using log4net;
using log4net.Layout;
using log4net.Repository.Hierarchy;

const string path = "your-log-name";
const string region = "eu-west-1";

var awsAppender = new AWSAppender
{
	Name = path,
	LogGroup = path,
	Region = region,
	Layout = new SimpleLayout(),
	//LogStreamNamePrefix = $"{DateTime.UtcNow:u}", // BUG Uncomment it, it works fine without it.
	LogStreamNameSuffix = "suffix"
};

awsAppender.ActivateOptions();

var logger = LogManager.GetLogger(path);
var l = (Logger)logger.Logger;
l.AddAppender(awsAppender);
l.Repository.Configured = true;

logger.Info($"guid = {Guid.NewGuid()} {DateTime.UtcNow:u}");
Console.Out.WriteLine("End");
```

### AWS .NET SDK and/or Package version used

AWS.Logger.Log4net 3.3.0
(AWS.Logger.Core 3.1.0)
(AWSSDK.CloudWatchLogs 3.7.0.5)
(AWSSDK.Core 3.7.0.6)
(log4net 2.0.12)

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10

**Comment by Rodriguevb** [comment]
The problem comes from the `:` character
Change `:` to `-` solves the problem..
```
LogStreamNamePrefix = $"{DateTime.UtcNow:u}".Replace(":", "-"), // BUG Uncomment it, it works fine without it.
```

**Comment by ashishdhingra** [comment]
> solves the problem..

@Rodriguevb Thanks for the confirmation. If this is no longer an issue, please confirm if it could be closed.
