### ISSUE TITLE
Not compatible with latest log4net

### ISSUE THREAD

**Issue by BillClarkDemTech** [aws/aws-logging-dotnet#214]
### Describe the bug

The latest version of log4net is 2.0.15, but the project file specifies 2.0.12.

### Expected Behavior

Building a setup project (Microsoft Visual Studio Installer Projects extension) with 2.0.15 should work.

### Current Behavior

Building a setup project produces the warning "Unable to find dependency 'LOG4NET' (Signature='669E0DDF0BB1AA2A' Version='2.0.12.0') of assembly 'AWS.Logger.Log4net.dll'". 

The deployed program will silently fail (i.e., it won't log to AWS) if 2.0.12 is not available on the user's system.

### Reproduction Steps

Ensure that log4net 2.0.12 is not available. Create and build a setup project using an installed copy of log4net 2.0.15. The setup will issue the above warning, and the deployed program will fail to log.

### Possible Solution

Change the reference in the project file to 2.0.15.

### AWS .NET SDK and/or Package version used

log4net 2.0.15

### Targeted .NET Platform

.NET Framework 4.7

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Similar to https://github.com/aws/aws-logging-dotnet/issues/162. Need to bump the version of `log4net` (also update the test cases, this might need to be done as part of separate release due to unreleased changes yet).

**Comment by ashishdhingra** [comment]
Change released in [AWS.Logger.Log4net 3.3.1](https://www.nuget.org/packages/AWS.Logger.Log4net/3.3.1).
