### ISSUE TITLE
ASP.NET Core Logging needs Profile property under Logging

### ISSUE THREAD

**Issue by albertlinga** [aws/aws-logging-dotnet#216]
### Describe the issue

New version of ASP.NET Core Logging requires setting configuration properties under the standard Logging object. In the readme.md of this repo, it wasn't specified that Profile property is also needed. e.g.

```
"Logging": {
   "Profile": "devprofile",
   "Region": "us-east-1",
   "LogGroup": "Sample",
   "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
   }
},
```

Either this is a documentation issue or a bug where the logging sdk doesn't fall back to the default config under AWS object.

### Links

https://github.com/aws/aws-logging-dotnet/blob/master/README.md

**Comment by ashishdhingra** [comment]
Hi @albertlinga,

Good afternoon.

Per code [here](https://github.com/aws/aws-logging-dotnet/blob/56055a8326b6cecd65d261d17fc8a95e063076ee/src/AWS.Logger.AspNetCore/AWSLoggerConfigSection.cs#L156), `Profile` property appears to be optional. Could you please share if you are getting any error while trying to use this library in your application? It should fall back to `default` profile if `Profile` property is missing. However, I do agree the `Readme` could be elaborated to specify supported properties. Kindly advise.

Thanks,
Ashish

**Comment by albertlinga** [comment]
This is the error I get if I don't specify the Profile in "Logging" object.

`Log Entry : 
1/27/2023 5:07:20 AM
  :
  :Amazon.Runtime.AmazonServiceException: Unable to get IAM security credentials from EC2 Instance Metadata Service.
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)`

This is my appsetttings.json
`{
    "Logging": {
        "Profile": "devprofile",
        "Region": "us-east-1",
        "LogGroup": "ContactSample",
        "LogLevel": {
            "Default": "Debug",
            "System": "Information",
            "Microsoft": "Information"
        }
    },
    "AWS": {
        "Profile": "devprofile",
        "Region": "us-east-1"
    },
    "ApplicationName": "ContactSample",
    "SendMessageQueueUrl": "https://sqs.us-east-1.amazonaws.com/151072946615/Contact",
    "AllowedHosts": "*"
}`

And this is the code in Program.cs
`// Add services to the container.
builder.Services.AddDefaultAWSOptions(builder.Configuration.GetAWSOptions());
builder.Services.AddRazorPages();
builder.Logging.ClearProviders();
builder.Logging.AddAWSProvider();
builder.Logging.SetMinimumLevel(LogLevel.Debug);

builder.Services.AddAWSService<IAmazonSQS>();
builder.Services.AddScoped<IContactQueueService, ContactQueueService>();`

**Comment by ashishdhingra** [comment]
> This is the error I get if I don't specify the Profile in "Logging" object.
> 
> ```
> Log Entry : 
> 1/27/2023 5:07:20 AM
>   :
>   :Amazon.Runtime.AmazonServiceException: Unable to get IAM security credentials from EC2 Instance Metadata Service.
>    at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()
>    at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
>    at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()
>    at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
> ```
> 
> This is my appsetttings.json
> 
> ```
> {
>     "Logging": {
>         "Profile": "devprofile",
>         "Region": "us-east-1",
>         "LogGroup": "ContactSample",
>         "LogLevel": {
>             "Default": "Debug",
>             "System": "Information",
>             "Microsoft": "Information"
>         }
>     },
>     "AWS": {
>         "Profile": "devprofile",
>         "Region": "us-east-1"
>     },
>     "ApplicationName": "ContactSample",
>     "SendMessageQueueUrl": "https://sqs.us-east-1.amazonaws.com/151072946615/Contact",
>     "AllowedHosts": "*"
> }
> ```
> 
> And this is the code in Program.cs
> 
> ```
> // Add services to the container.
> builder.Services.AddDefaultAWSOptions(builder.Configuration.GetAWSOptions());
> builder.Services.AddRazorPages();
> builder.Logging.ClearProviders();
> builder.Logging.AddAWSProvider();
> builder.Logging.SetMinimumLevel(LogLevel.Debug);
> 
> builder.Services.AddAWSService<IAmazonSQS>();
> builder.Services.AddScoped<IContactQueueService, ContactQueueService>();
> ```

@albertlinga Thanks for your reply. Quick question, where/how is your code executed and what is the application type? For certain applications (like ASP.NET), depending on where code is executed, default configured credentials (if configured under default profile) might not be accessible. Hence, credentials would need to be explicitly provided via some other means, which is profile app setting in this case.

But anyway, it would be good to mention about this optional profile setting in Readme.

Thanks,
Ashish

**Comment by albertlinga** [comment]
i am running my .net app locally launched via visual studio 2022

**Comment by ashishdhingra** [comment]
> i am running my .net app locally launched via visual studio 2022 and on Windows 11 OS. Also I don't think it's an issue of finding the shared credentials file in my home folder as the `builder.Services.AddAWSService<IAmazonSQS>();` was able to use the profile specified in the AWS key (default).

@albertlinga `Profile` key appears to be optional. Here are the reproduction steps:
- Used the sample web application in the repo which uses `AWS.Logger.AspNetCore` library, haing below `appSettings.json` (missing `Profile` key):
**appSettings.json
```JSON
{
  "Logging": {
    "Region": "us-east-1",
    "LogGroup": "AspNetCore.WebSample",
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "AllowedHosts": "*"
}
```
**appSettings.Development.json**
```JSON
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
}
```
- Configured `%USERPROFILE%\.aws\credentials` with `default` AWS credentials which has permissions listed at https://github.com/aws/aws-logging-dotnet#required-iam-permissions.
- Debugged via Visual Studio 2022 using IIS Express.

**RESULT:**
Following logs are written to CloudWatch:
```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                                                     message                                                                                                                      |
|---------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1675122496021 | [Information] WebSample.Startup: Check the AWS Console CloudWatch Logs console in us-east-1                                                                                                                                                      |
| 1675122496024 | [Information] WebSample.Startup: to see messages in the log streams for the                                                                                                                                                                      |
| 1675122496026 | [Information] WebSample.Startup: log group AspNetCore.WebSample                                                                                                                                                                                  |
| 1675122496356 | [Information] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: User profile is available. Using 'C:\Users\ashdhin\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.        |
| 1675122496624 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/2.0 GET https://localhost:44395/                                                                                                                                   |
| 1675122497150 | [Information] Microsoft.AspNetCore.Routing.EndpointMiddleware: Executing endpoint '/Index'                                                                                                                                                       |
| 1675122497350 | [Information] Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Route matched with {page = "/Index"}. Executing page /Index                                                                                                  |
| 1675122497380 | [Information] Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Executing handler method WebSample.Pages.IndexModel.OnGet - ModelState is Valid                                                                              |
| 1675122497386 | [Information] WebSample.Pages.IndexModel: Welcome to the AWS Logger. You are viewing the home page                                                                                                                                               |
| 1675122497390 | [Information] Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Executed handler method OnGet, returned result .                                                                                                             |
| 1675122497407 | [Information] Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Executing an implicit handler method - ModelState is Valid                                                                                                   |
| 1675122497414 | [Information] Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Executed an implicit handler method, returned result Microsoft.AspNetCore.Mvc.RazorPages.PageResult.                                                         |
| 1675122497626 | [Information] Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Executed page /Index in 265.8627ms                                                                                                                           |
| 1675122497630 | [Information] Microsoft.AspNetCore.Routing.EndpointMiddleware: Executed endpoint '/Index'                                                                                                                                                        |
| 1675122497748 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished in 1125.1523ms 200 text/html; charset=utf-8                                                                                                                             |
| 1675122497764 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/2.0 GET https://localhost:44395/lib/bootstrap/dist/css/bootstrap.css                                                                                               |
| 1675122497779 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/2.0 GET https://localhost:44395/lib/jquery/dist/jquery.js                                                                                                          |
| 1675122497781 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/2.0 GET https://localhost:44395/css/site.css                                                                                                                       |
| 1675122497784 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/2.0 GET https://localhost:44395/js/site.js?v=4q1jwFhaPaZgr8WAUSrux6hAuh0XDg9kPS3xIVq36I0                                                                           |
| 1675122497786 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/2.0 GET https://localhost:44395/lib/bootstrap/dist/js/bootstrap.js                                                                                                 |
| 1675122497795 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/2.0 GET https://localhost:44395/_framework/aspnetcore-browser-refresh.js                                                                                           |
| 1675122497797 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/2.0 GET https://localhost:44395/_vs/browserLink                                                                                                                    |
| 1675122497804 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished in 24.9296ms 200 application/javascript; charset=utf-8                                                                                                                  |
| 1675122497818 | [Information] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Sending file. Request path: '/js/site.js'. Physical path: 'D:\source\repros\ASPNetLoggingWebSample\wwwroot\js\site.js'                                                      |
| 1675122497823 | [Information] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Sending file. Request path: '/css/site.css'. Physical path: 'D:\source\repros\ASPNetLoggingWebSample\wwwroot\css\site.css'                                                  |
| 1675122497826 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished in 56.6627ms 200 application/javascript                                                                                                                                 |
| 1675122497829 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished in 57.8582ms 200 text/css                                                                                                                                               |
| 1675122497844 | [Information] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Sending file. Request path: '/lib/jquery/dist/jquery.js'. Physical path: 'D:\source\repros\ASPNetLoggingWebSample\wwwroot\lib\jquery\dist\jquery.js'                        |
| 1675122497846 | [Information] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Sending file. Request path: '/lib/bootstrap/dist/js/bootstrap.js'. Physical path: 'D:\source\repros\ASPNetLoggingWebSample\wwwroot\lib\bootstrap\dist\js\bootstrap.js'      |
| 1675122497849 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished in 78.9907ms 200 application/javascript                                                                                                                                 |
| 1675122497856 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished in 70.9527ms 200 application/javascript                                                                                                                                 |
| 1675122497859 | [Information] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Sending file. Request path: '/lib/bootstrap/dist/css/bootstrap.css'. Physical path: 'D:\source\repros\ASPNetLoggingWebSample\wwwroot\lib\bootstrap\dist\css\bootstrap.css'  |
| 1675122497863 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished in 98.4403ms 200 text/css                                                                                                                                               |
| 1675122497891 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished in 109.2939ms 200 text/javascript; charset=UTF-8                                                                                                                        |
| 1675122497998 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/2.0 GET https://localhost:44395/favicon.ico                                                                                                                        |
| 1675122498003 | [Information] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: Sending file. Request path: '/favicon.ico'. Physical path: 'D:\source\repros\ASPNetLoggingWebSample\wwwroot\favicon.ico'                                                    |
| 1675122498005 | [Information] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished in 7.1611ms 200 image/x-icon                                                                                                                                            |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

Kindly note the followin:
- If your credentials are configured under a named profile (other than `default`) profile, then you need to specify `Profile` key in appSettings.json
- The `credentials` file might not work when running the application under IIS since the application runs under webpool identity. You might want to configure credentials differently.

Please review.

Thanks,
Ashish

**Comment by albertlinga** [comment]
Thank you Ashish. I didn’t realize that it has to be literally the word “default”. Now I understand.
