### ISSUE TITLE
Where do we set AccessKey/SecretKey/credential, and the logStream? for Nlog

### ISSUE THREAD

**Issue by CharithW** [aws/aws-logging-dotnet#22]
When I went through the wiki , I noticed that there isn't anything regarding how to set Access Keys , Log stream etc.  It will be less confusing if we can  add how to do that.

**Comment by chazt3n** [comment]
why was this closed? this is a pretty huge omission if this is to be useful.

**Comment by klaytaybai** [comment]
@chazt3n, these can be set in the target.  Please refer to the README for samples of setting the target.  You can use the Credentials property for the keys/credentials and LogStreamNameSuffix to partly customize the log stream name.  Currently we don't provide support for any other LogStream name customization, but we may be adding support for custom prefixes shortly.

**Comment by chazt3n** [comment]
@klaytaybai thank you - I figured it out via your readme

I did not see it the first pass which is why I looked into Issues

That's my mistake
