### ISSUE TITLE
CloudWatch Log Streams get created but are empty

### ISSUE THREAD

**Issue by GSFAtArrow** [aws/aws-logging-dotnet#220]
### Describe the bug

We are using the AWS.Logger.Log4Net NuGet package to try to send our logs to CloudWatch. We have two log4net appenders - one for the file system (RollingFileAppender) and one for CloudWatch (AWSAppender). Logging appears in the files. The CloudWatch logging, however, succeeds in creating the AWS Log Streams but the Log Streams have no log entries in them. Naturally I suspected that the problem was that the application did not have the required AWS permissions but it does (CreateLogGroup, CreateLogStream, PutLogEvents, DescribeLogGroups).

### Expected Behavior

I expected the newly created Log Streams to include the same log entries as are included in the files.

### Current Behavior

The Log Streams are empty.

### Reproduction Steps

Create a .NET Framework 4.0 application and add the log4net and AWS.Logger.Log4Net NuGet packages. In the "public static void Register(HttpConfiguration config)" method add a call to this method to add the AWSAppender:-

```C#
private static void AddCloudWatchLogging()
{
    PatternLayout patternLayout = new PatternLayout
    {
        ConversionPattern = ConfigurationManager.AppSettings["CloudWatch_ConversionPattern"]
    };

    patternLayout.ActivateOptions();

    AWSAppender cloudWatchAppender = new AWSAppender()
    {
        LogGroup = ConfigurationManager.AppSettings["CloudWatch_LogGroup"],
        Region = ConfigurationManager.AppSettings["CloudWatch_Region"],
        Layout = patternLayout
    };

    cloudWatchAppender.ActivateOptions();

    Hierarchy hierarchy = (Hierarchy)log4net.LogManager.GetRepository();

    hierarchy.Root.AddAppender(cloudWatchAppender);

    hierarchy.Root.Level = log4net.Core.Level.Info;

    log4net.Config.BasicConfigurator.Configure(hierarchy);
}
```
Add some code to write some logging. Run the application and observe that the Log Streams are created but they contain no Log Entries.

### AWS .NET SDK and/or Package version used

AWSSDK.S3.3.7.103.25

### Targeted .NET Platform

.NET Framework 4.7.2

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Hi @GSFAtArrow,

Good afternoon.

Thanks for opening the issue? Could you please share the below:
- What is the type of application (or the Visual Studio template used)? Is it .NET Framework Web API project?
  - Is possible, please share the sample code solution (you may ZIP it and attach it to this issue) for faster troubleshotting. Also share the deployment/execution steps.
- How are you executing the application?
  - Are you executing from Visual Studio debugger? OR
  - Are you deploying to IIS and then executing the application?
- Where is the application deployed? If it on the standalone box or an EC2 instance?
- How are AWS credentials configured?
  Kindly note that if configured in default profile and application is deployed in IIS, then the user account under which application is being executed is not same as the logged in user for most cases.
- Could you enable the verbose logging using the below code and share the detailed logs:
```C#
Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());
```

**Comment by GSFAtArrow** [comment]
Hi Ashish,

> What is the type of application (or the Visual Studio template used)? Is it .NET Framework Web API project?

A .NET Framework 4 Web API application.

> Is possible, please share the sample code solution (you may ZIP it and attach it to this issue) for faster troubleshotting.

Unfortunately not, the application is large and the code is under IP protection but I have added the CloudWatch logger code in the first message above.

> Also share the deployment/execution steps. How are you executing the application?

The application is running in IIS on an EC2 instance.

> How are AWS credentials configured?

The application runs under the context of an AWS Role which has an AWS Profile which has the required CloudWatch permissions.

> Could you enable the verbose logging using the below code and share the detailed logs:

I already did this and couldn't find anything useful from the logs. The log file is very large now but I will try to extract some of it and add it here.

Thanks.

**Comment by GSFAtArrow** [comment]
Hi Ashish,
[log4netdiagnostics.txt](https://github.com/aws/aws-logging-dotnet/files/11565975/log4netdiagnostics.txt)

I have attached a small snippet from the log4netdiagnostics file. I couldn't find any error messages in here. This section appears to keep repeating.

**Comment by ashishdhingra** [comment]
> Hi Ashish,
> 
> > What is the type of application (or the Visual Studio template used)? Is it .NET Framework Web API project?
> 
> A .NET Framework 4 Web API application.
> 
> > Is possible, please share the sample code solution (you may ZIP it and attach it to this issue) for faster troubleshotting.
> 
> Unfortunately not, the application is large and the code is under IP protection but I have added the CloudWatch logger code in the first message above.
> 
> > Also share the deployment/execution steps. How are you executing the application?
> 
> The application is running in IIS on an EC2 instance.
> 
> > How are AWS credentials configured?
> 
> The application runs under the context of an AWS Role which has an AWS Profile which has the required CloudWatch permissions. I see that the CloudWatch Log Streams get created so I know that some permissions are being applied. My first assumption was that the Log Streams are empty because the PutLogEvents permission was missing but on checking I see that it is present.
> 
> > Could you enable the verbose logging using the below code and share the detailed logs:
> 
> I already did this and couldn't find anything useful from the logs. The log file is very large now but I will try to extract some of it and add it here.
> 
> Thanks.

@GSFAtArrow The logs shared by you are not verbose logs emitted by AWS SDK for .NET. Since you are using `.NET Framework 4` application, you may try following steps at [Logging with the AWS SDK for .NET](https://aws.amazon.com/blogs/developer/logging-with-the-aws-sdk-for-net/) to enable verbose logging. Depending on the options you enable, it should either write to log file you specify and/or SystemDiagnostics.

Also, if it is your test EC2 instance, you may also try using network monitoring tools (e.g. Fiddler) to examine why requests to put log events to CloudWatch logs are failing. Kindly note that it might take a while for logs to appear in CloudWatch logs, so kindly recheck if logs are still missing.

Also, just curious, have you somehow configured credentials at other location(s) mentioned in [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html)? Notice that Amazon EC2 instance metadata is resolved last. Also, an application in IIS runs under a different account by default, hence EC2 instance metadata credentials are the way to go (which you are already using).

Thanks,
Ashish

**Comment by GSFAtArrow** [comment]
Hi Ashish,

Thanks for the reply. You wrote:-

Since you are using .NET Framework 4 application, you may try following steps at [Logging with the AWS SDK for .NET](https://aws.amazon.com/blogs/developer/logging-with-the-aws-sdk-for-net/) to enable verbose logging

Apologies, I read through the link and can't find any mention of how to enable verbose logging for System.Diagnostics. Here is what our web.config section is:-

![image](https://github.com/aws/aws-logging-dotnet/assets/134046220/4eebf4b1-0ad7-42bb-b813-7b2a33a7254b)

What should I change here to enable verbose logging?

Thanks.

**Comment by ashishdhingra** [comment]
> Hi Ashish,
> 
> Thanks for the reply. You wrote:-
> 
> Since you are using .NET Framework 4 application, you may try following steps at [Logging with the AWS SDK for .NET](https://aws.amazon.com/blogs/developer/logging-with-the-aws-sdk-for-net/) to enable verbose logging
> 
> Apologies, I read through the link and can't find any mention of how to enable verbose logging for System.Diagnostics. Here is what our web.config section is:-
> 
> ![image](https://user-images.githubusercontent.com/134046220/243368287-4eebf4b1-0ad7-42bb-b813-7b2a33a7254b.png)
> 
> What should I change here to enable verbose logging?
> 
> Thanks.

@GSFAtArrow My apologies if this was unclear. Also refer `Allowed Elements` in [Configuration Files Reference for AWS SDK for .NET](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-ref.html) (only applies to .NET Framework). For `logging` section, you could select set `logResponses="Always"`. This would enable verbose logging.

Thanks,
Ashish
