### ISSUE TITLE
The category name probably should be passed to the custom formatter

### ISSUE THREAD

**Issue by onyxmaster** [aws/aws-logging-dotnet#23]
Including category name in target logs might be useful for metric filters. To prevent breaking existing code the new formatter might use some kind of intermediate object.
While I understand that I probably can work around this with decoration, this might really be useful when collecting detailed logs.

**Comment by qidydl** [comment]
The category name and log level, at minimum, are both pretty standard metadata I'd expect to see with each log event, like the standard Console formatter.
