### ISSUE TITLE
AWSLoggerConfig should expose AmazonCloudWatchLogsConfig.AuthenticationRegion

### ISSUE THREAD

**Issue by roemba** [aws/aws-logging-dotnet#255]
### Describe the feature

AWSLoggerConfig should expose a property called "AuthenticationRegion", that is passed to AmazonCloudWatchLogsConfig.AuthenticationRegion when set

### Use Case

For cases where the AWSLoggerConfig.ServiceUrl property is used, it can be unclear to an endpoint such as Localstack what 'region' it should associate with the given request. This causes it to always default to 'us-east-1'. 

The AuthenticationRegion property was introduced in the AWS .NET SDK to remedy this and allow the Client to hint to the endpoint the region without actually connecting to the region endpoint. 

Implementing this small change allows users to use the AWS Logger .NET for different regions than just 'us-east-1' with Localstack. The only way around this limitation currently is to implement an AWS Logger yourself using the Cloudwatch SDK.

### Proposed Solution

AWSLoggerConfig should expose a property called "AuthenticationRegion", that is passed to AmazonCloudWatchLogsConfig.AuthenticationRegion when set

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWS.Logger.Serilog 3.4.1

### Targeted .NET Platform

.NET 6, .NET 8

### Operating System and version

MacOs Sonoma 14.4.1

**Comment by ashishdhingra** [comment]
Appears to be useful feature request. Needs review with the team.

@roemba Feel free to contribute PR for this change. The change should work with all logging packages in this repository.

**Comment by ashishdhingra** [comment]
This has been released in `AWS.Logger.Core (3.3.2)` (refer [RELEASE.CHANGELOG](https://github.com/aws/aws-logging-dotnet/blob/master/RELEASE.CHANGELOG.md#release-2024-05-13))
