### ISSUE TITLE
Is it going to support .Net Standard 2.0

### ISSUE THREAD

**Issue by mshirishkumar** [aws/aws-logging-dotnet#27]
Is AWS logging log4net is going to have support of .net standard 2.0?

**Comment by sunilraskar** [comment]
No. To work with AWS you need minimum .net framework 4.5.

**Comment by maynardflies** [comment]
I added a PR for support of .NET Standard 1.5 to bring it in line with the implementation for NLog, #32

**Comment by spati2** [comment]
Thanks @maynardflies . Closing this issue.
