### ISSUE TITLE
Log groups stop collecting entries after some variable amount of time

### ISSUE THREAD

**Issue by akotranza** [aws/aws-logging-dotnet#34]
We're seeing this issue with dotnet core 2 applications using the latest AWS.Logger.AspNetCore package. The applications and logging functions as expected after a deployment but after some amount of time (have seen ~1 day up to ~1 week) there are no new entries in the log group.

The setup is vanilla, the log provider is added in Configure if the environment is production (in Startup.cs)
`loggerFactory.AddAWSProvider(Configuration.GetAWSLoggingConfigSection());`

And the relevant config in appsettings.json is

```
"AWS.Logging": {
    "LogGroup": "MyGroupName",
    "LogLevel": {
      "MyNamespace" : "Information",
      "System": "Warning",
      "Microsoft": "Information",
      "Default": "Information"
    }
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "MyNamespace" : "Information",
      "System": "Warning",
      "Microsoft": "Information",
      "Default": "Information"
    }
  }
```

The applications continue to function as expected, processing requests, which indicates that calls are continuing to be made to the ILogger instance (which is DI'd into all controllers and other objects that need logging). But no logs are collected in CloudWatch after some amount of time has passed. 

The only workaround I've found is to redeploy the application. This causes the log groups in CloudWatch to once again collect entries.

I've seen this with applications running on EC2 c4.large instances or t2.small instances and in both private and public VPC subnets. The instances are not under much load when the logging stops working, minimal CPU use and lots of available memory.

Is this a known problem w/ either the package or CloudWatch? How would we go about debugging this further?

**Comment by akotranza** [comment]
After reading through the code more closely, I see that I should have reported this problem as happening on the Log Stream level.

With this understanding, I can see that our older dotnet core 1.0 application stacks that used this package had the same issue; we'd just never before seen every log stream in the log group go dry.

**Comment by costleya** [comment]
We have deployed a fix for this in AWS.Logger.Core 1.6/1.7. You can get it by either updating your chosen logging dependency to latest (AWS.Logger.AspNetCore), or downloading version 1.7 of core directly.

Let us know if this does not resolve the issue.
