### ISSUE TITLE
Add ITextFormatter to Serilog  plugin so can format messages

### ISSUE THREAD

**Issue by robertwnorris** [aws/aws-logging-dotnet#36]
I’m using the Serilog plugin and want to format by output as JSON. I’ve done the changes locally which work great and are quite small. Basically, I’ve added an ITextFormatter and an optical parameter to the extension methods and then updated the Emit method to use the formatter if one has been passed.

I’d like to get this code back into the project. I’d be grateful if you could let me know how to do this i.e. would you like me to create a pull request?

Cheers,
Rob

**Comment by HenryMaoSydney** [comment]
https://github.com/aws/aws-logging-dotnet/pull/41

**Comment by normj** [comment]
Closing as this is being tracked by the PR https://github.com/aws/aws-logging-dotnet/pull/41
