### ISSUE TITLE
AWS.Logger.NLog nuspec file has no dependencies declared

### ISSUE THREAD

**Issue by Trigger2991** [aws/aws-logging-dotnet#4]
Installing the NuGet package for AWS.Logger.NLog does not automatically install the AWS.Logger.Core package as it is not added as a dependency in the nuspec file. Please add to save time and trouble following the instructions on this blog post that don't work as the core package is missing.
https://aws.amazon.com/blogs/developer/amazon-cloudwatch-logs-and-net-logging-frameworks/

**Comment by spati2** [comment]
Thank you for pointing out this oversight. We will submit a fix with AWS.Logger.Core as a dependency package for AWS.Logger.NLog

**Comment by spati2** [comment]
Please refer to the latest NLog package at https://www.nuget.org/packages/AWS.Logger.NLog/. Thanks for bringing this to our attention
