### ISSUE TITLE
Evaluate NLog parameters in AwsTarget Class

### ISSUE THREAD

**Issue by seroche** [aws/aws-logging-dotnet#47]
Hi,

I found out that NLog parameters are NOT evaluated when they are passed to the AWSTarget. 
Any variable, or renderers used within these parameters will not get evaluated.

For instance:
```
        [RequiredParameter]
        public string LogGroup
        {
            get { return _config.LogGroup; }
            set { _config.LogGroup = value; }
        }
```

Does not evaluate code like: `${when:when='${environment:ASPNETCORE_ENVIRONMENT}'=='Production':inner=prd:else=uat}`

To make it work, I had to change the AwsTarget class and call SimpleLayout.Evaluate when assigning value to AWSLoggerConfig.

```
        [RequiredParameter]
        public string LogGroup
        {
            get => _config.LogGroup;
            set => _config.LogGroup = SimpleLayout.Evaluate(value);
        }
```

I'm not sure it's a good practice, but it solved my "issue"

**Comment by spati2** [comment]
Hi @seroche , is the use case here to decide on the logGroup name based on the environment in which you are running?

**Comment by seroche** [comment]
Yes exactly. 

I'm maintaining a huge amount of internal apis. With these variable I can maintain one file that can be re-used by all my APIs in all my environments!

**Comment by snakefoot** [comment]
@seroche Created #71 that resolves your issue (once it is released).

**Comment by snakefoot** [comment]
See a nuget-package has been released a week ago:

https://www.nuget.org/packages/AWS.Logger.NLog/

**Comment by klaytaybai** [comment]
Thanks @snakefoot
