### ISSUE TITLE
ASP.NET Core Log event ID support

### ISSUE THREAD

**Issue by ksks88** [aws/aws-logging-dotnet#50]
Is there some way to pass [Log event ID](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1&tabs=aspnetcore2x#log-event-id) to formatter and then filter logs by that same ID?

Wright now our formatter looks like this:
`formatter: (logLevel, message, exception) => $"[{DateTime.UtcNow}] {logLevel}: {message} \n {exception}"));` and I can't find a way to pass log event ID except inside a message.

I think this feature would be very useful and it's kind of a "core" for every logging library.

**Comment by normj** [comment]
We don't have that support now but it would be a good feature to add. I'll try add it but if you are up for a pull request the change should be pretty minimal in this function. https://github.com/aws/aws-logging-dotnet/blob/f3e766d206b67a350081f9f58f0167a99c3ee724/src/AWS.Logger.AspNetCore/AWSLogger.cs#L65

Just depends on how you want to format it.

**Comment by ksks88** [comment]
Hey @normj,

I would love to do the PR, but I need some more details.

I would like to let user format it and pass it in customFormatter but unfortunately there is no optional argument for Func, in that case I would break existing code with change:
`private readonly Func<LogLevel, object, Exception, EventId, string> _customFormatter;`.

As I see one solution would be to add another optional _customFormatter argument in ctor with the above signature. Please let me know what do you think.

Thanks,

**Comment by normj** [comment]
I have created PR https://github.com/aws/aws-logging-dotnet/pull/90 that will add this support.

**Comment by normj** [comment]
In version 2.0.0 of AWS.Logger.AspNetCore you can set the `IncludeEventId` to true in your appsettings.json and then event id will be included in the log message.

https://github.com/aws/aws-logging-dotnet/blob/master/RELEASE.CHANGELOG.md#release-2019-06-27
