### ISSUE TITLE
NLog ReconfigureExistingLoggers does not pick up change to AWSTarget.LogGroup

### ISSUE THREAD

**Issue by otto-urpelainen-enoro** [aws/aws-logging-dotnet#51]
I have a problem with AWS.Logger.NLog 1.1.7 on .Net Core 2.1 and programmatically changing CloudWatch Log Group. As far as I understand, setting property **AWSTarget.LogGroup** and then running **NLog.LogManager.ReconfigExistingLoggers** should redirect logs to new log group. However what I am seeing is logs still going to the original log group.

The following code reproduces the problem:

**NLog.config**:
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwExceptions="true">
  <extensions>
    <add assembly="NLog.AWS.Logger" />
  </extensions>
  <targets>
    <target
      name="aws"
      xsi:type="AWSTarget"
      logGroup="AwsNlogTest"
      region="eu-west-1"
      layout="${message}"/>
  </targets>
  <rules>
    <logger name="*" minlevel="Debug" writeTo="aws" />
  </rules>
</nlog>
```

**ReconfigTest.cs**:
```
using NLog;
using NLog.AWS.Logger;

namespace AwsNlogReconfig
{
    class ReconfigTest
    {
        static void Main(string[] args)
        {
            Logger logger = LogManager.GetCurrentClassLogger();
            logger.Info("Message to original log group"); // Works as expected

            var awsTarget = LogManager.Configuration.FindTargetByName("aws") as AWSTarget;
            awsTarget.LogGroup += "-suffix";
            LogManager.ReconfigExistingLoggers();

            logger.Info("Message to new log group"); // Still sends to original log group
        }
    }
}
```

**Comment by snakefoot** [comment]
`AWSLoggerCore` doesn't react to all changes in `AWSLoggerConfig` after it has initialized/connected.

Possible work around is to re-assign the NLog-configuration. This causes NLog to close all targets, and initialize them again (Creates a new `AWSLoggerCore`)

```
var awsTarget = LogManager.Configuration.FindTargetByName("aws") as AWSTarget;
awsTarget.LogGroup += "-suffix";
LogManager.Configuration = LogManager.Configuration;   // Close and reinit ALL targets (not all like this)
```

**Comment by otto-urpelainen-enoro** [comment]
Thank you for the workaround! I already solved my problem by setting things up in a way that does not require reconfiguration.

Is it the indented that AWSLoggerConfig is ignored? I.e. is this a valid bug or just a case of me misinterpreting the specs?

**Comment by snakefoot** [comment]
> @otto-urpelainen-enoro Is it the indented that AWSLoggerConfig is ignored?

No idea. Not the developer of AWS-Logging. But based on the current activity-level, then Amazon doesn't give it much priority or thought.

**Comment by ashishdhingra** [comment]
Hi @otto-urpelainen-enoro, 

Since workaround provided by @snakefoot worked for you, please confirm if this issue could be closed.

Thanks,
Ashish

**Comment by cartermq** [comment]
No none of these suggestions worked so I would not close the issue.
