### ISSUE TITLE
AWS.Logger.AspNetCore does not respect LogLevels in Lambda

### ISSUE THREAD

**Issue by mshahzad100** [aws/aws-logging-dotnet#52]
I am using AWS.Logger.AspNetCore (1.2.7) and Aws.Logger.Core(1.1.8)
I followed the websamples example to implement Logging in my Lambda function.
When i run locally i am able to see the logs on console which respects the log levels defined in appsettings.
When the code runs on aws lambda it doesnt respect the AWS.Logging defined in the configs and somehow always shows "INFORMATION" logs and above and ignores all my "DEBUG" logs. Here is what i have in my appsettings

"Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "AWS.Logging": {
    "Region": "us-east-1",
    "LogGroup": "AspNetCore.WebSample",
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  }

**Comment by beerdog** [comment]
Same here when running in EC2.
Debug logs are never shown regardless of loglevel in logfile.
Any progress on this?

**Comment by girishnuli** [comment]
Just used this in a webapi that is deployed as a lambda function. It seems like other than Information and Error, all other log levels are not getting logged to Cloudwatch logs. 

A second behavior I have observed is that when running in development mode on local machine, logging happens to the defined log group in Cloudwatch. But when deployed using Staging environment, the log is always written to the Lambda role log group.

**Comment by HY1221** [comment]
Just had a quick view of the code, this API push the message into a list. And another thread keeps looking at this list and push them to Cloud Watch until the list is idle or contains more than 5 messages. However, AWS may kills the lambda after the main thread completes.

I am trying to use the following library. 
https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.Logging.AspNetCore

**Comment by normj** [comment]
Yes, **AWS.Logger.AspNetCore** should not be used in Lambda because it relies on a background thread. **Amazon.Lambda.Logging.AspNetCore** does not rely on on a background thread and basically just forwards to ILambdaContext.Logging.LogLine.

**Comment by HY1221** [comment]
@normj, thank you for the confirmation. Just an advice, could you please mentioned this on the homepage? So people won't get confused any more.

**Comment by normj** [comment]
@HY1221 That is a good suggestion, thanks!

**Comment by normj** [comment]
Updated README.md https://github.com/aws/aws-logging-dotnet/commit/43553b82dcb4adf13c939f6c7d48266210d0ae8b

**Comment by normj** [comment]
Looks like for external providers the default minimum logging level is set to Informational. You can explicitly call `SetMinimumLevel` to Debug so that Debug messages will be sent to CloudWatch Logs.

```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .ConfigureLogging(logging =>
        {
            // When you need logging below set the minimum level. Otherwise the logging framework will default to Informational for external providers.
            logging.SetMinimumLevel(LogLevel.Debug);
        })
        .UseStartup<Startup>();
```
