### ISSUE TITLE
NLog successfully creates the logging group, but not any log events

### ISSUE THREAD

**Issue by jdk339** [aws/aws-logging-dotnet#54]
Here is where I configure the logger with code:

```
public ILogger GetLogger() {
 if (logger != null) {
  return logger;
 }
 var config = new LoggingConfiguration();

 var consoleTarget = new ColoredConsoleTarget();
 config.AddTarget("console", consoleTarget);

 var awsTarget = new AWSTarget() {
  LogGroup = "NLog.UnitTestLibrary",
   Region = "us-east-1"
 };
 config.AddTarget("aws", awsTarget);

 config.LoggingRules.Add(new LoggingRule("*", LogLevel.Debug, consoleTarget));
 config.LoggingRules.Add(new LoggingRule("*", LogLevel.Debug, awsTarget));

 LogManager.Configuration = config;
 return LogManager.GetCurrentClassLogger();
}
```

This is how I call it:

```
_logger.Debug(response.Content.ReadAsStringAsync().Result);
 _logger.Debug("hey!");
```

The AWS profile has the following access:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "logs:DescribeLogGroups"
      ],
      "Resource": [
        "arn:aws:logs:*:*:*"
      ]
    }
  ]
}
```
I also tried it with a profile with full access, and it still didn't work. What am I missing here? Is there a way I can debug this?

**Comment by snakefoot** [comment]
@jdk339 If you are willing to try a custom build based on the code from PR #53 :

https://github.com/aws/aws-logging-dotnet/issues/56#issuecomment-441117090 (PreRelease Nuget-packages to put in local nuget repository)

Then you can activate the NLog Internal Logger and it might give more details about what is failing. Remember to call `NLog.LogManager.Shutdown()` before app-exit.

**Comment by snakefoot** [comment]
New release is available that improves flush to CloudWatch: https://www.nuget.org/packages/AWS.Logger.NLog/1.3.1

**Comment by snakefoot** [comment]
@jdk339 Have your issue been resolved with the updated version? (New ver. 1.4.0 is now also available: https://www.nuget.org/packages/AWS.Logger.NLog)

**Comment by ashishdhingra** [comment]
Hi @jdk339, 

Please advise if the your issue is resolved with the updated version at https://www.nuget.org/packages/AWS.Logger.NLog.

Thanks,
Ashish
