### ISSUE TITLE
Expiration on Logs

### ISSUE THREAD

**Issue by afick** [aws/aws-logging-dotnet#55]
Is there a way to set the expiration / Delete retention policy for the logs?

**Comment by klaytaybai** [comment]
Hi @afick, sorry for not getting to this earlier.  There is currently nothing in this library that supports modifying the retention policy for log groups.  However you can use the [AWSSDK.CloudWatchLogs] package's PutRetentionPolicy method to add a retention policy of an existing log group.(https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/CloudWatchLogs/MCloudWatchLogsPutRetentionPolicyPutRetentionPolicyRequest.html).  I'll add the addition of a configuration/setup step to allow setting retention policy in this library to the feature request backlog.  Thanks for the suggestion.

**Comment by spicoflorin** [comment]
Hello!

We are facing the same issue that the CloudWatch group is set up to never expire. Can you please give me an update if thre is any configuration related where we can set up the in a file, that for example to expire logs after 15 days?
