### ISSUE TITLE
Method 'get_ServiceMetadata' in type 'Amazon.CloudWatchLogs.AmazonCloudWatchLogsClient' from assembly 'AWSSDK.CloudWatchLogs, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604' does not have an implementation.

### ISSUE THREAD

**Issue by daymansiege** [aws/aws-logging-dotnet#57]
Trying to use AWS Target for NLog or log4net, both fail with the same error.

*NLog*:
```
var config = new LoggingConfiguration();
var awsTarget = new AWSTarget()
{
	LogGroup = Environment.GetEnvironmentVariable("AWS_LAMBDA_LOG_GROUP_NAME"),
	Region = Environment.GetEnvironmentVariable("AWS_DEFAULT_REGION")
};

config.AddTarget("aws", awsTarget);
config.LoggingRules.Add(new LoggingRule("*", LogLevel.Debug, awsTarget));

LogManager.Configuration = config;
LogManager.ThrowConfigExceptions = true;
LogManager.ThrowExceptions = true;
```

```
One or more errors occurred. (Exception occurred in NLog): AggregateException
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

at NLog.LoggerImpl.<>c__DisplayClass1_0.<Write>b__1(Exception ex)
at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
at NLog.LoggerImpl.WriteToTargetWithFilterChain(Target target, FilterResult result, LogEventInfo logEvent, AsyncContinuation onException)
at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
at ...
at ...
Target AWSTarget Target[(unnamed)] failed to initialize.: NLogRuntimeException
Method 'get_ServiceMetadata' in type 'Amazon.CloudWatchLogs.AmazonCloudWatchLogsClient' from assembly 'AWSSDK.CloudWatchLogs, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604' does not have an implementation.: TypeLoadException
at AWS.Logger.Core.AWSLoggerCore..ctor(AWSLoggerConfig config, String logType)
at NLog.AWS.Logger.AWSTarget.InitializeTarget()
at NLog.Targets.Target.Initialize(LoggingConfiguration configuration)
```

*log4net*:

```
Hierarchy hierarchy = (Hierarchy)LogManager.CreateRepository(Repository);
PatternLayout patternLayout = new PatternLayout();
patternLayout.ConversionPattern = "%-4timestamp [%thread] %-5level %logger %ndc - %message%newline";
patternLayout.ActivateOptions();

AWSAppender appender = new AWSAppender();
appender.Layout = patternLayout;
appender.LogGroup = Environment.GetEnvironmentVariable("AWS_LAMBDA_LOG_GROUP_NAME");
appender.Region = Environment.GetEnvironmentVariable("AWS_DEFAULT_REGION");
appender.ActivateOptions();

hierarchy.Root.AddAppender(appender);
hierarchy.Root.Level = Level.All;
hierarchy.Configured = true;
```

```
LambdaException
at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
Method 'get_ServiceMetadata' in type 'Amazon.CloudWatchLogs.AmazonCloudWatchLogsClient' from assembly 'AWSSDK.CloudWatchLogs, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604' does not have an implementation.: TypeLoadException
at AWS.Logger.Core.AWSLoggerCore..ctor(AWSLoggerConfig config, String logType)
at AWS.Logger.Log4net.AWSAppender.ActivateOptions()
at ...
```

**Comment by normj** [comment]
This was caused by an issue with our SDK release on Wednesday. The issue was there was a change to AWSSDK.Core that breaks older service clients. We are working on a fix now. 

To work around the issue add an explicitly reference to AWSSDK.CloudWatchLogs in your project to 3.3.6.3 so that the latest compatible version is used.

**Comment by daymansiege** [comment]
Thank you guys!
Is there any chance that dependencies for the package AWS.Logger.NLog will reference more recent version? 
Also, do you know if using NLog in Lambda is a good idea (due to async flushing, where we have issues like this: https://github.com/aws/aws-logging-dotnet/issues/35)?

**Comment by normj** [comment]
@daymansiege do you mean the AWS SDK dependencies or the NLog dependencies?

I wouldn't recommend using these libraries in Lambda because there would be no guarantee that the back ground threads would finish before Lambda freezes the compute container.

**Comment by daymansiege** [comment]
@normj I mean AWS SDK dependencies of the AWS.Logger.NLog and/or AWSSDK.CloudWatchLogs. If you don't add latest AWSSDK.Core explicitly, it will link older version of it. 
When I tried, it was AWS.Logger.NLog (1.4.0) -> AWSSDK.CloudWatchLogs (3.3.4) -> AWSSDK.Core (3.3.17) instead of AWSSDK.CloudWatchLogs (3.3.6.4) -> AWSSDK.Core (3.3.27.1).

**Comment by snakefoot** [comment]
@daymansiege It should be trivial to make an NLog-Target that calls the LambdaLogger-directly:

[Configure call of lambda at runtime](https://github.com/NLog/NLog/wiki/MethodCall-target#configure-call-of-lambda-at-runtime)

You can also create your own custom NLog-target in a seperate assembly:

https://github.com/NLog/NLog/wiki/How-to-write-a-custom-target

Then just make sure not to use NLog-Targets-Async-mode. If not able to call Flush before Lambda-completion.

**Comment by daymansiege** [comment]
@snakefoot, yes, thank you!
That's what I'm thinking about: 
1. Does it make sense to write own NLog target or wait until async flushing works for Lambda in AWS.Logger.NLog?
2. OR just use own non-NLog logging service instead and throw away NLog usage for Lambda at all as most targets are async and will not work correctly if I try to use somethimg like fluentd/logstash or whatever?

**Comment by snakefoot** [comment]
> Does it make sense to write own NLog target

You just create a target that takes ILambdaContext and use its ILambdaLogger. Not that difficult.

> OR just use own non-NLog logging service instead and throw away NLog usage for Lambda

If you are not using any of the NLog features (Common Logger-interface, filtering-logic, structured-logging, layout-context-capture-logic), then just stop using NLog. But just because AWS-NLog-Target is currently faulty, then it doesn't mean that NLog is broken and it is impossible to forward the NLog output to a different target.
