### ISSUE TITLE
No documentation in the README for Serilog

### ISSUE THREAD

**Issue by prairieapps** [aws/aws-logging-dotnet#58]
It would be great to get an example of how to use AWS.Logger.Serilog, it doesn't seem to be included in the README or the samples directory. Next to no examples online either.

**Comment by gsaadeh** [comment]
+1 looking for an example as well as I am currently receiving an exception when deployed to AWS. I have to same configuration from your test.

**Comment by DouglasHammon** [comment]
+1

**Comment by andyfurniss4** [comment]
+1

I can't figure out how to give Serilog my AWS credentials.

**Comment by normj** [comment]
The README has been updated with Serilog documentation.

**Comment by gitblit** [comment]
Thanks for this update.  It was very timely for me and I was able to quickly demonstrate functional message/text logging.

One surprising thing: Neither CloudWatch nor CloudWatch Insights seem able to access the structued log properties which I know are collected in the Serilog context of my app.  Is there additional configuration required in the sink or in CloudWatch to view and filter on structured log properties?

**Comment by ce-Tom** [comment]
+1 for Examples 

For people having problems with Credentials or Parameter discovery heres what i found.

Set your profile! In your appsettings Serilog section you can set Profile, LogGroup, LogStreamNamePrefix. See https://github.com/aws/aws-logging-dotnet/blob/master/src/AWS.Logger.SeriLog/AWSLoggerSeriLogExtension.cs for all the config properties you have to work with

For Parameter discovery in CloudWatch you need to render the log as JSON, by default it uses text rendering. Simply add a JSON TextFormatter (https://github.com/serilog/serilog/wiki/Formatting-Output)

```
                    Log.Logger = new LoggerConfiguration()
                        .ReadFrom.Configuration(hostContext.Configuration)
                        .WriteTo.AWSSeriLog(hostContext.Configuration, textFormatter: new CompactJsonFormatter())
                        .CreateLogger();
```

Setting a formatter needs to be done in code (above). Setting it via config (see below) doesn't work.

```
    "WriteTo": [
      {
        "Name": "AWSSeriLog",
        "textFormatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact"
      }
    ],
```

If anyone figures out how to set the output template please let me know!

**Comment by ashishdhingra** [comment]
Hi @prairieapps,

Good morning.

I do notice that the Readme has been updated to add information for [Serilog](https://github.com/aws/aws-logging-dotnet#serilog) which also has added link to [code sample](https://github.com/aws/aws-logging-dotnet/blob/master/samples/Serilog). Please let me know if this issue could be closed.

Thanks,
Ashish
