### ISSUE TITLE
Cloud watch with log4net API

### ISSUE THREAD

**Issue by princykv** [aws/aws-logging-dotnet#6]
Hi,

I am trying to integrate log4net API to push all application logs directly to Cloud  watch. This is working fine. But message in json format is truncated. I am trying to log API request and response content. My API is using following JSON format for request/response. 

{
	"Name": "SyncAPI",
	"Message": {
		"LastSyncNo": 100
	},
	"Status": {
		"Success": false,
		"Code": 422
	}
}

Following layout pattern is used in log4net configuration. Could you please help me to log data in above mentioned JSON format using log4net?

`
<layout type="AWSAppender.Core.Layout.PatternLayout, AWSAppender.Core">
      <conversionPattern value="%date [%thread] %-5level  %message" />
 </layout>
`

Regards,
Princy

**Comment by PavelSafronov** [comment]
This looks like a question for the [CloudWatchAppender repo](https://github.com/camitz/CloudWatchAppender).
