### ISSUE TITLE
Can I create a stream per log level?

### ISSUE THREAD

**Issue by yahya99223** [aws/aws-logging-dotnet#63]
When AWS decides to create a new log stream?
When logging, inside my logGroup I want only few streams, each for a log level, is this possible? does AWS provide such ability?
Note: No automatic log streams should be created

**Comment by normj** [comment]
That is an interesting idea but we don't have the support currently.

**Comment by snakefoot** [comment]
@yahya99223 If possible to have multiple AWS-Client running in the same application, then you can configure multiple AWS-targets in NLog. One for each LogLevel.
