### ISSUE TITLE
Provide ability to get the current stream name

### ISSUE THREAD

**Issue by adamrkerr** [aws/aws-logging-dotnet#64]
This is similar to #1 , but likely less complicated.

Can we provide a public method on the core logger implementation (and interface) that returns the name of the current log stream? I understand from the related issue why allowing full configuration of the stream name is difficult. However, I've looked at the source for  AWSLoggerCore and found this:

`_currentStreamName = DateTime.Now.ToString("yyyy/MM/ddTHH.mm.ss") + " - " + _config.LogStreamNameSuffix;`

How hard would it be to provide a method that returns `_currentStreamName`?

I have one application that writes to cloud watch, and another that needs to display messages from the log. It would be very helpful if I knew exactly which stream to pull. The Cloud Watch SDK allows searching for streams, but it can search only by the beginning of the name, which I currently have no way to know.

**Comment by klaytaybai** [comment]
Hi @adamrkerr, that seems like a reasonable improvement with few barriers.  I can't make any promises on when or if this will be added, but it is unlikely that it will be added until our re:Invent conference is over at the end of the month.  Thanks for the feedback.

**Comment by adamrkerr** [comment]
@klaytaybai  I could submit a PR for it, if you're OK with that?

**Comment by klaytaybai** [comment]
@adamrkerr, that could be helpful.  However, we are not doing any releases until next week, so it would take at a minimum that long to get merged in.

**Comment by normj** [comment]
I don't think there is a way to expose the stream name that would be useful since your application isn't ever directly holding a reference to any of these loggers. With the latest release you can now set a prefix for the log stream which you could use to search. Hopefully that will help your use case.

https://github.com/aws/aws-logging-dotnet/blob/master/RELEASE.CHANGELOG.md#release-2019-06-27
