### ISSUE TITLE
Error setting configuration in NLog and Xamarin

### ISSUE THREAD

**Issue by hanchhanch** [aws/aws-logging-dotnet#68]
Hi,
I'm trying to use the NLog plugin in a Xamarin project, but gets this error message when trying to set the configuration 
The error is thrown in the line NLog.LogManager.Configuration = config; 

error msg:
System.TypeLoadException: Could not resolve type with token 01000055 (from typeref, class/assembly Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain, AWSSDK.Core, Version=3.3.0.0, Culture=neutral, 

The Application is a Xamarin Forms targeting .netstandardcore. 
This is the configuration I'm trying to set programmatically:

`var config = new NLog.Config.LoggingConfiguration();
var consoleTarget = new NLog.Targets.ConsoleTarget();
config.AddTarget("console", consoleTarget);
config.LoggingRules.Add(new NLog.Config.LoggingRule("*", NLog.LogLevel.Debug, consoleTarget));

var awsTarget = new NLog.AWS.Logger.AWSTarget()
{
    LogGroup = "NLog.ProgrammaticConfigurationExample",
    Region = "us-east-1",
    Credentials = AWSClient.GetDefaultCredentials()
};
config.AddTarget("aws", awsTarget);
config.LoggingRules.Add(new NLog.Config.LoggingRule("*", NLog.LogLevel.Debug, awsTarget));
NLog.LogManager.Configuration = config;`

If I remove the aws target, everything works normally.

Any ideas?
Thanks

**Comment by snakefoot** [comment]
Updated #67 so usage of CredentialProfileStoreChain happens in isolated method. Only activated when having configured ProfileName to something else than "default".

**Comment by scolestock** [comment]
I'm finding in a Xamarin.iOS setting that at **link** time, you get the following error.  Any insights?
We can resolve temporarily by pulling in AWSLoggerCore.cs and commenting out code such that DetermineCredentials will call FallbackCredentialsFactory.GetCredentials();

`MTOUCH: Error MT2101: Can't resolve the reference 'Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain', referenced from the method 'Amazon.Runtime.AWSCredentials Polaris.Mobile.Core.AWSLogger.AWSLoggerCore::LookupCredentialsFromProfileStore(Polaris.Mobile.Core.AWSLogger.AWSLoggerConfig)' in 'AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. (MT2101) (PolarisExperience.iOS)`

**Comment by snakefoot** [comment]
@scolestock + @hanchhanch Still have the issue with the latest release: 

https://www.nuget.org/packages/AWS.Logger.NLog (ver. 1.4.0)

**Comment by ashishdhingra** [comment]
Hi @hanchhanch,

Please confirm if you still have the issue with the latest release at [https://www.nuget.org/packages/AWS.Logger.NLog](https://www.nuget.org/packages/AWS.Logger.NLog) or if this issue could be closed.

Thanks,
Ashish
