### ISSUE TITLE
Setting up basic credentials using awsKey and secretToken

### ISSUE THREAD

**Issue by vickyrathee** [aws/aws-logging-dotnet#69]
The documentation didn't have any mention of how to setup `BasicAWSCredentials`. I spent some time to make it work, posting here for to benefit other users...

```
var awsCredentials = new Amazon.Runtime.BasicAWSCredentials("awsKey", "secretToken");
var awsTarget = new AWSTarget()
{
	LogStreamNameSuffix = "api-",
	LogGroup = "group-name",
	Region = "us-east-1",
	Credentials = awsCredentials,
	Layout = "${longdate}\t${level:uppercase=true}\t${message}${exception:format=tostring}"
};
config.AddTarget("aws", awsTarget);
config.AddRuleForOneLevel(LogLevel.Fatal, awsTarget);
```

Working perfectly fine 👍

**Comment by klaytaybai** [comment]
Hi @vickyrathee, thank you for your feedback and contribution.  I'm sorry if you took longer on this than you had hoped.  Here is some more documentation on setting up credentials with .NET

https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Runtime/TBasicAWSCredentials.html
https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html
