### ISSUE TITLE
Mark AWS.Logger.Core as a dependency of AWS.Logger.NLog?

### ISSUE THREAD

**Issue by coultonluke** [aws/aws-logging-dotnet#7]
I followed the instructions on the README for AWS Logging and I was hoping that I could get up and running quite quickly as I've been using the AWSSDK for a quite a while now within my projects.

I installed the package into my project, along with NLog to start logging.

I kept on getting an error message, sporadically:

> Target cannot be found: 'AWSTarget'

I was scratching my head, because even with the sample project I wasn't able to get it to run when I deleted the project Nlog.AWS.Logging from the sample project and replaced it with the use of the Nuget package.

After close inspection and playing around with the solution a bit more, adding and removing references and Nuget packages I finally got it to work by installing AWS.Logger.Core into my project.

> Install-Package AWS.Logger.Core

Once I did this, it worked perfectly fine and I could see logs in CloudWatch.

I wondered whether this should be added to the documentation for this project, I can't find it in there - I could have missed it though.  Also I wondered if the Nuget package `AWS.Logger.NLog` should have ` AWS.Logger.Core` marked as a dependency?

I have been using the non-modularised AWSSDK, which is if possibly why I was more likely to have fallen into this trap, I'm going to look at moving to the modularised version now.

**Comment by PavelSafronov** [comment]
You are correct, this is an oversight on our part. We're tracking this in issue #4. Closing this issue.
