### ISSUE TITLE
does  AWS.Logger.AspNetCore support Conversion pattern? 

### ISSUE THREAD

**Issue by chsandeepkumar** [aws/aws-logging-dotnet#70]
Does AWS.Logger.AspNetCore support conversion pattern? can we configure the pattern in appseting.json?
`PatternLayout patternLayout = new PatternLayout();

    patternLayout.ConversionPattern = "%-4timestamp [%thread] %-5level %logger %ndc - %message%newline";
    patternLayout.ActivateOptions();`

**Comment by klaytaybai** [comment]
Hi @chsandeepkumar,

I'm not sure about integrating the PatternLayout from Log4Net, but you can define a custom formatter.

"A custom formatter which accepts a LogLevel, a state, and an exception and returns the formatted log message."
Here is an example from the [AspNetCore sample](https://github.com/aws/aws-logging-dotnet/blob/master/samples/AspNetCore/WebSample/Startup.cs):
```
loggerFactory.AddAWSProvider(this.Configuration.GetAWSLoggingConfigSection(), 
                formatter: (logLevel, message, exception) => $"[{DateTime.UtcNow}] {logLevel}: {message}");
```

**Comment by chsandeepkumar** [comment]
Hi @klaytaybai 

Thanks for response and i think this should solve my problem. I will try this approach
