### ISSUE TITLE
Required IAM Policy 

### ISSUE THREAD

**Issue by gianbasagre** [aws/aws-logging-dotnet#74]
I am using an EC2 IAM role to access AWS resources inside my EC2 instance. I applied the following policy on my IAM role but the library still seems to have issues creating/accessing CloudWatch Logs:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "logs:DescribeLogGroups"
      ],
      "Resource": [
        "arn:aws:logs:*:*:*"
      ]
    }
  ]
}
```

Are there any more permissions required? I even have CloudWatchLogsFullAccess but that doesn't seem to work still. I checked that all operations are allowed via AWS CLI inside my EC2 instance.

**Comment by klaytaybai** [comment]
What is the specific error that you are getting?  Those are the only permissions required for this library to log to CloudWatch.

Did you specify the role with policy when you created the EC2 instance?

**Comment by gianbasagre** [comment]
The error I'm getting is:

```
Application startup exception
System.NullReferenceException: Object reference not set to an instance of an object.
at <My.Application>.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in <My.Application>/Startup.cs:line 81
End of stack trace from previous location where exception was thrown ---
at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```
> Did you specify the role with policy when you created the EC2 instance?

Yes I did. I even tried the AWS CLI commands inside the EC2 instance and it was working. 

I posted the issue here as well: https://stackoverflow.com/questions/54991309/aws-logger-aspnetcore-ec2-instance-role

**Comment by gianbasagre** [comment]
I found the issue, there is another `appsettings.json` file from another project that's overriding my settings.
