### ISSUE TITLE
Support for ILoggingBuilder

### ISSUE THREAD

**Issue by Kralizek** [aws/aws-logging-dotnet#75]
Microsoft is discoraging using `ILoggerFactory` in favor of `ILoggingBuilder`.

```csharp
// before
var factory = new LoggerFactory();
factory.AddConsole();

// now
services.AddLogging(logging => logging.AddConsole());
```

It would be great if we could get a variation of `AddAWSProvider` that accepts a `ILoggingBuilder` instead of `ILoggerFactory` as first parameter.

**Comment by klaytaybai** [comment]
Hi @Kralizek, thank you for the suggestion.  We'll evaluate adding this.

**Comment by Kralizek** [comment]
For those like me looking for a workaround, here it is:

```csharp
logging.AddProvider(new AWSLoggerProvider(context.Configuration.GetAWSLoggingConfigSection()));
```

**Comment by qidydl** [comment]
The way the Microsoft logging infrastructure handles configuration is also a bit different, there's a lot of conventions there, e.g. everything being in the root "Logging" section, with provider-specific configuration being routed in based on the alias. I think filtering might also happen in the logging infrastructure, so specific providers don't necessarily need to reimplement filtering by log level. Microsoft's loggers are all under https://github.com/aspnet/Extensions/tree/master/src/Logging so the source there can be really useful.

**Comment by normj** [comment]
I have created PR https://github.com/aws/aws-logging-dotnet/pull/90 to add support for ILoggingBuilder

**Comment by normj** [comment]
Closing as this has shipped with the latest version.
