### ISSUE TITLE
User-defined log stream prefix

### ISSUE THREAD

**Issue by bartpio** [aws/aws-logging-dotnet#83]
In the prior state, a user-defined log stream _suffix_ may be provided, but the _prefix_ is always of the form yyyy/mm/dd. In some usage scenarios, this can prevent efficient filtering of log streams when enumerating the streams in a group. 

Allow an optional LogStreamNamePrefix configuration, which if specified, is used as the first segment of the prefix. If this configuration is engaged, the yyyy/mm/dd system-generated form will be used as the second segment of the prefix. The design invariant that a unique date-based segment is included in the stream name is maintained.

If the LogStreamNamePrefix configuration is not engaged, behavior will match the prior state; log stream names will begin with the yyyy/mm/dd segment.

**Comment by klaytaybai** [comment]
Thanks for bringing some attention to this and working on the PR.  I'm assuming that you're aware of https://github.com/aws/aws-logging-dotnet/issues/1.

**Comment by normj** [comment]
Closing this and we will use your PR to track this feature request https://github.com/aws/aws-logging-dotnet/pull/84
