### ISSUE TITLE
Config File not found

### ISSUE THREAD

**Issue by avikenjale** [aws/aws-logging-dotnet#86]
I have a ASP.NET core web api deploy on AWS lambda.

I followed all the steps as explained in the documentation.  However, when my code is deployed to AWS Lambda it throws the following error as it is not finding `log4net.config` file

>Application startup exception: System.IO.FileNotFoundException: Could not find file '/var/task/wwwroot\config\log4net.config'.

Is there something else need to be performed to handle this situation?

**Comment by klaytaybai** [comment]
Hi @avikenjale, could you please verify that you have followed the steps in the [README](https://github.com/aws/aws-logging-dotnet#apache-log4net), including setting the file property ''Copy to Output Directory' for the log4net.config to Copy Always?

**Comment by avikenjale** [comment]
Yes, I did that. 

Meanwhile, this worked when I kept log config file at the root level instead of under `wwwroot\config`.

**Comment by ashishdhingra** [comment]
Hi @avikenjale,

Good afternoon.

I was going through backlog issues and came across this guidance question. I can understand that you want to store configuration files on the config folder for better management.

Looks like by default, `log4net.config` is expected to be at the root of the application. Please try adding the below setting in application's config file and let me know if it works:

```XML
<?xml version="1.0"?>
<configuration>
  <appSettings>
    <add key="log4net.Config" value="config/log4net.config" />
  </appSettings>
</configuration>
``` 

You may also try to import external config files in a .NET application (refer Microsoft's documentation for more details) and see if it works.

Kindly let me know if this works and if this issue could be closed.

Thanks,
Ashish
