### ISSUE TITLE
Nlog to cloudwatch creates delays on services

### ISSUE THREAD

**Issue by Jhordan92** [aws/aws-logging-dotnet#87]
This is my current nlog config, and we've been noticing a delay in methods excution, and even going as far as throwing errors such as this Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown awssdk.core. I honestly don't see the problem

> <?xml version="1.0" encoding="utf-8" ?>
> <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
>       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>       autoReload="true"
>       internalLogLevel="Info"
>       internalLogFile="internal-nlog.txt">
> 
>   
>   <extensions>
>     <add assembly="NLog.Web.AspNetCore"/>
>     <add assembly="NLog.Targets.CloudWatchLogs" />
>   </extensions>
> 
>   
>   <targets>
>     
>     <target xsi:type="File" name="allfile" fileName="nlog-all-${shortdate}.log"
>             layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring} " />
> 
>     
> 
>     <target name="AWSLog" xsi:type="CloudWatchLogs" AWSRegion="us-west-2"
>             AWSAccessKeyId="AWSAccessKeyId" AWSSecretKey="AWSSecretKey"
>             LogGroupName="LogGroupName" LogStreamName="LogStreamName" layout="${longdate} [${threadid}] ${level} ${logger} [${ndc}] - ${message} ${exception:format=tostring}"/>
>   </targets>
> 
>   
>   <rules>
>     
>     <logger name="Microsoft.*" maxlevel="Info" final="true" />
>     
>     <logger name="*" minlevel="Trace" writeTo="allfile" />
>     <logger name="*" minlevel="Debug" writeTo="AWSLog" />
>   </rules>
> </nlog>

**Comment by Jhordan92** [comment]
```
<?xml version="1.0" encoding="utf-8" ?>
 <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       autoReload="true"
       internalLogLevel="Info"
       internalLogFile="internal-nlog.txt">
 
   <!-- enable asp.net core layout renderers -->
   <extensions>
     <add assembly="NLog.Web.AspNetCore"/>
     <add assembly="NLog.Targets.CloudWatchLogs" />
   </extensions>
 
   <!-- the targets to write to -->
   <targets>
     <!-- write logs to file  -->
     <target xsi:type="File" name="allfile" fileName="nlog-all-${shortdate}.log"
             layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring} " />
 
     <!-- another file log, only own logs. Uses some ASP.NET core renderers -->
 
     <target name="AWSLog" xsi:type="CloudWatchLogs" AWSRegion="us-west-2"
             AWSAccessKeyId="AWSAccessKeyId" AWSSecretKey="AWSSecretKey"
             LogGroupName="LogGroupName" LogStreamName="LogStreamName" layout="${longdate} [${threadid}] ${level} ${logger} [${ndc}] - ${message} ${exception:format=tostring}"/>
   </targets>
 
   <!-- rules to map from logger name to target -->
   <rules>
     <!--Skip non-critical Microsoft logs and so log only own logs-->
     <logger name="Microsoft.*" maxlevel="Info" final="true" />
     <!-- BlackHole without writeTo -->
     <logger name="*" minlevel="Trace" writeTo="allfile" />
     <logger name="*" minlevel="Debug" writeTo="AWSLog" />
   </rules>
 </nlog>
```

**Comment by klaytaybai** [comment]
Hi @Jhordan92, could you please try modifying your config to more closely match that from our README and sample?  That may help you out.  If it doesn't let me know.  

Things to keep in mind:

- The type should be AWSTarget
- The LogStreamName is not supported by AWSTarget.  You can currently only specify a LogStreamNameSuffix

**Comment by Jhordan92** [comment]
> Hi @Jhordan92, could you please try modifying your config to more closely match that from our README and sample? That may help you out. If it doesn't let me know.
> 
> Things to keep in mind:
> 
> * The type should be AWSTarget
> * The LogStreamName is not supported by AWSTarget.  You can currently only specify a LogStreamNameSuffix

I changed to AwsTarget to avoid the delay in the services:

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Info"
      internalLogFile="c:\logs\provider\internal-nlog.txt">

  <!-- enable asp.net core layout renderers -->
  <extensions>
    <add assembly="NLog.AWS.Logger" />
  </extensions>

  <!-- the targets to write to -->
  <targets>
    <!-- write logs to file  -->
 
    <target name="aws" type="AWSTarget" logGroup="Group" region="region"/>
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
   
    <logger name="*" minlevel="Debug" writeTo="aws" />
  </rules>
</nlog>
```
That's the current config, and that's when I get the error in my other post

**Comment by snakefoot** [comment]
So this issue can be resolved. Since it is not related to `AWSTarget`, but by using `CloudWatchLogs` (Target completely unrelated to this repository).

**Comment by Jhordan92** [comment]
Ok, then this issue is discarded, but then the issue of the misterious exception when using AWSTarget, what would that be?

**Comment by snakefoot** [comment]
> issue of the misterious exception when using AWSTarget, what would that be?

Better keep that discussion in the other issue you already have.
