### ISSUE TITLE
[SeriLog] LogError with Exception will break CloudWatch searching

### ISSUE THREAD

**Issue by jasonycw** [aws/aws-logging-dotnet#89]
`_logger.LogError(exception, "message")` will create logs in CloudWatch that is not searchable with JSON filter pattern.

https://github.com/aws/aws-logging-dotnet/blob/035436aefcdfec2320ca9e798960c294b10bc969/src/AWS.Logger.SeriLog/AWSSink.cs#L37-L53

This sends log message to CloudWatch with the fomat
``` JSON
{
	"timestamp": 1433190184356,
	"message": "{JSON message}\n\n Exception stack track"
	"ingestionTime": 1433190494190
}
```

This format is not supported/valid message according to CloudWatch support, that's why when we use `_logger.LogError(exception, "message")`, the message on CloudWatch is not searchable with JSON filter pattern like `{ $.Level = "Error" }` and the metric filters will not work properly.

**Comment by normj** [comment]
Version 1.4.0 of AWS.Logger.SeriLog was shipped with the fix. Now the exception will no longer be appended to the message when a text formatter like the JSON formatter is used relying on the formatter to handle formatting the exception.
