### ISSUE TITLE
Cannot set ServiceUrl to use with LocalStack

### ISSUE THREAD

**Issue by gsfataviva** [aws/aws-logging-dotnet#93]
AWSTarget does not have a ServiceUrl property. The consequence is that it cannot be set and therefore AWSTarget cannot be used with LocalStack (I want to set the ServiceUrl to http://localhost:4582 - the LocalStack CloudWatch service).

Can you add this property?

Guy

**Comment by snakefoot** [comment]
Created  #94. But not in a position to test it.

**Comment by gsfataviva** [comment]
@snakefoot Many thanks for the very fast resolution :-).

**Comment by bebenekmarcin** [comment]
I was looking to made exactly the same change to support setting ServiceUrl. My case is different as I have code deployed to server which don't have access to the internet. I have created PrivateLink between CloudWatch and my EC2. Then I needed option to set ServiceUrl.
Can you please let me know when this will be available on nuget?

**Comment by snakefoot** [comment]
@klaytaybai + @normj Guess it has been resolved with #94 and the latest releases:

https://github.com/aws/aws-logging-dotnet/blob/master/RELEASE.CHANGELOG.md

**Comment by normj** [comment]
Yes, thanks for the reminder @snakefoot
