### ISSUE TITLE
20 unit tests failed

### ISSUE THREAD

**Issue by dimmy-timmy** [aws/aws-logging-dotnet#95]
20 tests failed on clean repo. Master branch
![image](https://user-images.githubusercontent.com/1872946/61613267-8d14b980-ac69-11e9-90b8-bc55c1728161.png)

**Comment by ashishdhingra** [comment]
Hi @dimmy-timmy,

Good morning.

I was going through the issue backlog and came across this one. I ran some tests at high level and all appear to be passing (with default credentials file).  Please confirm if this issue could be closed.

Thanks,
Ashish
