### ISSUE TITLE
Avoid calling DescribeLogGroups in scenarios where we don't need to auto-create missing Log Groups

### ISSUE THREAD

**Issue by bartpio** [aws/aws-logging-dotnet#98]
During initialization, the library checks to see if the configured Log Group exists (via a call to DescribeLogGroups), and creates the Log Group if it doesn't already exist.

The call to [DescribeLogGroups](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_DescribeLogGroups.html), if my understanding is correct, requires permission to enumerate all log groups in the AWS account. The DescribeLogGroups [permission](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazoncloudwatchlogs.html) does include a log group ARN, but it seems that the log group name portion of the ARN must be a wildcard in order to work.

In some scenarios, with permissions locked down tight (to prevent account-wide enumeration of resources), and Log Groups pre-created, the call DescribeLogGroups prevents use of the library, artificially. 

AWSLoggerConfig should have a property of this form:

```
/// <summary>
/// Determines whether or not to create a new Log Group, if the one specified by <see cref="LogGroup"/> doesn't already exist
/// If false (the default), the Log Group is created if it doesn't already exist. This requires logs:DescribeLogGroups
/// permission to determine if the group exists, and logs:CreateLogGroup permission to create the group if it doesn't already exist.
/// If true, creation of Log Groups is disabled. Logging functions only if the specified log group already exists.
/// When creation of log groups is disabled, logs:DescribeLogGroups permission is NOT required.
/// </summary>
public bool DontCreateLogGroup { get; set; }
```

**Comment by klaytaybai** [comment]
Thanks for working on this.
